### ISSUE TITLE
struct.error running pathway_pipeline.py

### ISSUE THREAD

**Issue by bakerccm** [picrust/picrust2#102]
I'm trying to run the following command, and getting an error:

`pathway_pipeline.py --input /n/piercefs/protected/Users/cbaker/soil/picrust2/out/EC_metagenome_out/pred_metagenome_contrib.tsv.gz --out_dir /n/piercefs/protected/Users/cbaker/soil/picrust2/out/pathways_out --map /n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/pathway_mapfiles/metacyc_path2rxn_struc_filt_pro.txt --intermediate /n/piercefs/protected/Users/cbaker/soil/picrust2/out/pathways_intermediate --proc 4 --regroup_map /n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/pathway_mapfiles/ec_level4_to_metacyc_rxn.tsv
`

Standard out says:

```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 344, in _sendback_result
    exception=exception))
  File "/n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 240, in put
    self._writer.send_bytes(obj)
  File "/n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/home04/cbaker/miniconda3/envs/picrust2/bin/pathway_pipeline.py", line 271, in <module>
    main()
  File "/n/home04/cbaker/miniconda3/envs/picrust2/bin/pathway_pipeline.py", line 186, in main
    print_cmds=args.print_cmds)
  File "/n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 352, in pathway_pipeline
    regroup_mapfile, proc)
  File "/n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 1178, in regroup_func_ids
    for func_subset in function_chunks)
  File "/n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/n/home04/cbaker/miniconda3/envs/picrust2/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

I first got this error while running the full picrust2_pipeline.py. I tried cleaning my conda environment using `conda clean --all` and reinstalling picrust2 with 

`conda create -n picrust2 -c bioconda -c conda-forge picrust2=2.2.0_b `

and then just re-running the pathway_pipeline.py command since that was the part that appeared to have failed, but same error.

Here's what I get from `conda list`:

```
(picrust2) [cbaker@boslogin03 ~]$ conda list
# packages in environment at /n/home04/cbaker/miniconda3/envs/picrust2:
#
_libgcc_mutex             0.1                        main  
_r-mutex                  1.0.1               anacondar_1    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
binutils_impl_linux-64    2.31.1               h6176602_1  
binutils_linux-64         2.31.1               h6176602_8  
biom-format               2.1.7           py36h3010b51_1002    conda-forge
bwidget                   1.9.11                        0    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.14.12           h80bd089_1005    conda-forge
certifi                   2019.9.11                py36_0    conda-forge
click                     7.0                        py_0    conda-forge
coverage                  4.5.4            py36h516909a_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
epa-ng                    0.3.5                he860b03_0    bioconda
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
future                    0.17.1                py36_1000    conda-forge
gappa                     0.4.0                he860b03_0    bioconda
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_8    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gfortran_impl_linux-64    7.3.0                hdf63c60_1  
gfortran_linux-64         7.3.0                h553295d_8  
glib                      2.56.2            had28632_1001    conda-forge
glpk                      4.65              he80fd80_1002    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_8    conda-forge
h5py                      2.10.0          nompi_py36h513d04c_100    conda-forge
harfbuzz                  1.9.0             he243708_1001    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1103    conda-forge
hmmer                     3.2.1                hf484d3e_1    bioconda
icu                       58.2              hf484d3e_1000    conda-forge
importlib_metadata        0.23                     py36_0    conda-forge
joblib                    0.13.2                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
libidn2                   2.1.1                h14c3975_0    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libunistring              0.9.10               h14c3975_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
make                      4.2.1             h14c3975_2004    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.2           py36h95a1406_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.1           py36hb3f55d8_0    conda-forge
pango                     1.40.14           hf0c64fd_1003    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
picrust2                  2.2.0_b                    py_0    bioconda
pip                       19.2.3                   py36_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pytest                    5.1.2                    py36_0    conda-forge
pytest-cov                2.7.1                      py_0    conda-forge
python                    3.6.7             h381d211_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
r-base                    3.5.1             he45234b_1005    conda-forge
r-castor                  1.4.1             r35h0357c0b_1    conda-forge
r-naturalsort             0.1.3           r35h6115d3f_1002    conda-forge
r-nloptr                  1.2.1             r35h0357c0b_1    conda-forge
r-rcpp                    1.0.2             r35h0357c0b_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
scipy                     1.3.1            py36h921218d_2    conda-forge
setuptools                41.2.0                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
tktable                   2.10                 h555a92e_2    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wget                      1.20.1               h90d6eec_0    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.8                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge

```

Any help much appreciated!

Thanks!

**Comment by gavinmdouglas** [comment]
Hey @bakerccm ,

Thanks for posting all of these details. Would you mind sharing the file `pred_metagenome_contrib.tsv.gz` with me to see if I can reproduce the error?

If so, you can email me at: ![gmail_screenshot](https://user-images.githubusercontent.com/12489683/65387350-f3c35b80-dd1c-11e9-95f2-fb25972af317.jpg)

 Another thing to check would be whether the command works on a single processor.

Thanks,

Gavin

**Comment by bakerccm** [comment]
Hi @gavinmdouglas, thanks for the quick reply! I tried running the command on a single processor and it completed, so that works for me. I'll email you a link to `pred_metagenome_contrib.tsv.gz` in case you still want to try and reproduce the error. Cheers, Chris

**Comment by gavinmdouglas** [comment]
Hey @bakerccm,

Glad to hear it finished on a single processor and thanks for sending the file.

I was able to reproduce the error on my system, but I'm not sure what's causing the problem. My guess is that it's due to a memory limitation when multiprocessing with joblib (the python package the script is using - see similar error [here](https://github.com/scikit-learn/scikit-learn/issues/3313)).

What's the rough richness of your samples? I think there might be many more OTUs per sample than what I have used in my validations, which I think is why I've never run into this before.

Either way I'll be sure to troubleshoot this further for next release - thanks for pointing it out.


Gavin

**Comment by bakerccm** [comment]
Oops sorry, forgot to reply to this earlier … My OTU table has just over 8000 OTUs. Individual samples have a median richness of more like 300-400 OTUs. Hope that helps and thanks again for your assistance with this!

Cheers,
Chris

On 24 Sep 2019, at 10:20 am, Gavin Douglas <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @bakerccm<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bakerccm&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=cC4cEiK-UacffPmBO9rWPH231dLIPq2Y641F2xDOBZU&m=jEF7I9OV_zFRCWY5WLEVPUxw1MFXCt0lnDIyXj3iFV8&s=CiB9SLMJ07I7UJJr396dkcTQIFgktDzFK4tHMg-BpnA&e=>,

Glad to hear it finished on a single processor and thanks for sending the file.

I was able to reproduce the error on my system, but I'm not sure what's causing the problem. My guess is that it's due to a memory limitation when multiprocessing with joblib (the python package the script is using - see similar error here<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_scikit-2Dlearn_scikit-2Dlearn_issues_3313&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=cC4cEiK-UacffPmBO9rWPH231dLIPq2Y641F2xDOBZU&m=jEF7I9OV_zFRCWY5WLEVPUxw1MFXCt0lnDIyXj3iFV8&s=xGPuHyf2Oht5lp3qmT7d3LmJ4rHTgyGTH2BfHCmzzFU&e=>).

What's the rough richness of your samples? I think there might be many more OTUs per sample than what I have used in my validations, which I think is why I've never run into this before.

Either way I'll be sure to troubleshoot this further for next release - thanks for pointing it out.

Gavin
