### ISSUE TITLE
  raise ValueError("Index {col} invalid".format(col=col))

### ISSUE THREAD

**Issue by aassie** [picrust/picrust2#104]
Hello there,

Thank you for this very useful tool, 

I am currently using the last part of the pipeline to run the pathway prediction tool. I have tweaked the first part of the pipeline because we do experiments where used mixes of known bacteria together and then we are trying to reconstruct a virtual metagenome out of it. 

I have one dataset where it worked perfectly but then for another, I have the following error:

I running `pathway_pipeline.py` as follow

 ```pathway_pipeline.py -i $outfd/$cname.biom.txt        -o $outfd/path_$cname\_biom         -p 4         --per_sequence_abun $outfd/$cname.asv.scaled.csv         --per_sequence_function $outfd/$cname.EC.base.matrix.txt         --per_sequence_contrib         --coverage ```

And I get the error below, any idea on what the issue should be?

Thank you for your help!

Adrien

```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/picrust2/bin/pathway_pipeline.py", line 271, in <module>
    main()
  File "/usr/local/anaconda3/envs/picrust2/bin/pathway_pipeline.py", line 209, in main
    print_cmds=args.print_cmds)
  File "/usr/local/anaconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 492, in pathway_pipeline
    print_opt=print_cmds)
  File "/usr/local/anaconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 732, in per_sequence_contrib_levels
    dtype={'sequence': str})
  File "/usr/local/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/usr/local/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/usr/local/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/io/parsers.py", line 2135, in read
    index, names = self._make_index(data, alldata, names)
  File "/usr/local/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1579, in _make_index
    index = self._get_simple_index(alldata, columns)
  File "/usr/local/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1611, in _get_simple_index
    i = ix(idx)
  File "/usr/local/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1606, in ix
    raise ValueError("Index {col} invalid".format(col=col))
ValueError: Index sequence invalid
```

**Comment by aassie** [comment]
My bad, I had a typo in `sequence` it work now 😅
