### ISSUE TITLE
problem while running metagenome_pipeline.py: 'str' and 'int'

### ISSUE THREAD

**Issue by ruchi19flowchart** [picrust/picrust2#108]
I have executed below picrust command:
**python3.5 /opt/app/picrust2/scripts/picrust2_pipeline.py -s rep_seq_1.fa -i otu_table_with_taxo.tsv -o picrust2_out --processes 40 --stratified --per_sequence_contrib --in_traits COG,EC,KO,PFAM,TIGRFAM**

While running below exceptions have been identified:

Error running this command:
metagenome_pipeline.py --input otu_table_with_taxo.tsv --function picrust2_out/COG_predicted.tsv.gz --min_reads 1 --min_samples 1 --out_dir picrust2_out/COG_metagenome_out --max_nsti 2.0 --marker picrust2_out/marker_predicted_and_nsti.tsv.gz --strat_out

Standard output of failed command:
""

Standard error of failed command:
"11 of 5967 ASVs were above the max NSTI cut-off of 2.0 and were removed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/ops.py", line 2001, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/computation/expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for /: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/metagenome_pipeline.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/app/picrust2/scripts/metagenome_pipeline.py", line 122, in <module>
    main()
  File "/opt/app/picrust2/scripts/metagenome_pipeline.py", line 104, in main
    skip_norm=args.skip_norm)
  File "/opt/app/picrust2/picrust2/metagenome_pipeline.py", line 75, in run_metagenome_pipeline
    norm_filename=norm_output)
  File "/opt/app/picrust2/picrust2/metagenome_pipeline.py", line 256, in norm_by_marker_copies
    axis="index")
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/ops.py", line 2030, in f
    level=level)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/ops.py", line 1917, in _combine_series_frame
    return self._combine_match_index(other, func, level=level)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 5106, in _combine_match_index
    new_data = func(left.values.T, right.values).T
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/ops.py", line 2003, in na_op
    result = masked_arith_op(x, y, op)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/ops.py", line 1009, in masked_arith_op
    com.values_from_object(yrav[mask]))
TypeError: unsupported operand type(s) for /: 'str' and 'int'
"
**I'm not able to get where the problem is? Need help if possible.**

**Comment by gavinmdouglas** [comment]
Hey @ruchi19flowchart,

I think the most likely problem is that there is a taxonomy column in your OTU table (`otu_table_with_taxo.tsv `), which the tool is trying to interpret as just another sample column so it's confused why the values are strings rather than numbers.


Best,

Gavin

**Comment by ruchi19flowchart** [comment]
**I'm sharing you the otu_table_with_taxo.tsv snapshot as below:**

# Constructed from biom file
#OTU ID	M.1
4479944	4.0
35231	34.0
988537	20.0
2562097	1.0
590450	1.0
4369469	4.0
813717	6.0
614607	16.0
1146636	1.0
1085229	1.0
4298282	3.0

the otu table for one sample where the first column is representing OUT ID and its number.

**Comment by ruchi19flowchart** [comment]
Problem solved.. as i have provided **tsv** converted format of biom, which was actually running upto hsp.py program but not accepting in metagenome_pipeline.py.

**Comment by gavinmdouglas** [comment]
Hi @ruchi19flowchart ,

What version of PICRUSt2 are you running? I'm not able to reproduce this problem - legacy TSV format should work.

**Comment by ruchi19flowchart** [comment]
I'm using PICRUSt2 2.2.0-b. Its running upto gene family identification. I 'm getting the above exceptions after that.
