### ISSUE TITLE
pathway_pipeline.py step error 

### ISSUE THREAD

**Issue by sandipansamaddar** [picrust/picrust2#123]
Hi,
I ran picrust2 several times with my datasett and it worked fine but now I am trying with a different dataset which is similar (ASV table and biom file) but it is showing error in pathway.pipeline step. I am unable to find out what is the problem. I tried several times but every time I reach the pathway step it runs and shows same error. The other steps works perfectly fine. The error which I am getting is :

```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 344, in _sendback_result
    exception=exception))
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 240, in put
    self._writer.send_bytes(obj)
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/samaddar/anaconda3/envs/picrust2/bin/pathway_pipeline.py", line 271, in <module>
    main()
  File "/home/samaddar/anaconda3/envs/picrust2/bin/pathway_pipeline.py", line 209, in main
    print_cmds=args.print_cmds)
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 352, in pathway_pipeline
    regroup_mapfile, proc)
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 1178, in regroup_func_ids
    for func_subset in function_chunks)
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

```
If I can get some help on how to solve the problem it will be really appreciated. I am also attaching a screenshot of file which I used as the input for pathway predictions step.
![Screenshot at 2020-05-29 10-00-07](https://user-images.githubusercontent.com/30172935/83285863-dd1ab180-a193-11ea-824b-24983f2b9da9.png)

Thank you,

Sandipan

**Comment by sandipansamaddar** [comment]
Hello,
Any update? I am worried is my comment posted?

Best,

Sandipan

**Comment by gavinmdouglas** [comment]
Hi @sandipansamaddar,

Sorry I missed this. What version are you running and what exact command are you using?


Thanks,

Gavin

**Comment by sandipansamaddar** [comment]
Hi,
Thanks @gavinmdouglas and congrats on you Nat Bio paper.

I installed picrust 2 using latest release v2.3.0-b. I am having problem with the pathway prediction step. The code I used is :
```
pathway_pipeline.py -i EC_metagenome_out/pred_metagenome_contrib.tsv.gz \
                    -o pathways_out -p 5
```
and the error I am getting is : 

```
joblib.externals.loky.process_executor._RemoteTraceback:"""`
Traceback` (most recent call last):
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 357, in _sendback_result
    exception=exception))
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 244, in put
    self._writer.send_bytes(obj)
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/samaddar/anaconda3/envs/picrust2/bin/pathway_pipeline.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/samaddar/picrust2-2.3.0-b/scripts/pathway_pipeline.py", line 272, in <module>
    main()
  File "/home/samaddar/picrust2-2.3.0-b/scripts/pathway_pipeline.py", line 210, in main
    verbose=args.verbose)
  File "/home/samaddar/picrust2-2.3.0-b/picrust2/pathway_pipeline.py", line 352, in pathway_pipeline
    regroup_mapfile, proc)
  File "/home/samaddar/picrust2-2.3.0-b/picrust2/pathway_pipeline.py", line 1180, in regroup_func_ids
    for func_subset in function_chunks)
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 540, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/samaddar/anaconda3/envs/picrust2/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```
Other steps seem to work fine. But I cannot figure out what is the problem going on.

Any suggestions will be appreciated.

Thanks,

Sandipan

**Comment by gavinmdouglas** [comment]
Thanks! Hmm do you still run into this problem if you use just one core? Either way would you mind sharing your input file with me at: 
![gmail_screenshot](https://user-images.githubusercontent.com/12489683/83695192-f70f2680-a5cf-11ea-8489-44b2e811d3d8.jpg)


Thanks,

Gavin

**Comment by sandipansamaddar** [comment]
I emailed you the files. With one core the process got killed. No idea what is happening.

Take care,

Sandipan

**Comment by Melody5528** [comment]
Hi @gavinmdouglas ,

Thank you so much for your help.

I follow your advice and was able to finish one round of the PiCrust2 analysis for the first time, WOW!

Thanks again!!!

**Comment by gavinmdouglas** [comment]
Quick note that I think this error was related to high memory usage related to having ~10,000 ASVs. Filtering out rare ASVs resolved the issue.
