### ISSUE TITLE
Plugin error from q2-picrust2

### ISSUE THREAD

**Issue by yuyulim** [picrust/picrust2#132]
I'm trying to run the follow command and getting an error:

` qiime picrust2 full-pipeline    --i-table table.qza    --i-seq rep-seqs.qza    --output-dir q2-picrust2_output    --p-threads 56    --p-hsp-method pic    --p-max-nsti 2    --verbose`
Standard out says:
```Traceback (most recent call last):
  File "/home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/q2cli/commands.py", line 328, in __call__
    results = action(**arguments)
  File "</home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/decorator.py:decorator-gen-477>", line 2, in full_pipeline
  File "/home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/jtc/q2-picrust2-2019.10_0/q2_picrust2/_full_pipeline.py", line 70,in full_pipeline
    verbose=highly_verbose)
TypeError: full_pipeline() got an unexpected keyword argument 'processes'
```
```
Traceback (most recent call last):
  File "/home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/q2cli/commands.py", line 328, in __call__
    results = action(**arguments)
  File "</home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/decorator.py:decorator-gen-477>", line 2, in full_pipeline
  File "/home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/jtc/q2-picrust2-master/q2-picrust2-master/q2_picrust2/_full_pipeline.py", line 70, in full_pipeline
    verbose=highly_verbose)
TypeError: full_pipeline() got an unexpected keyword argument 'processes'
```
I first got this error while I use the q2-plugin `q2-picrust2-2019.10-0`, then I tried again with the plugin `q2-picrust2-master`, and I got the same error, what's wrong with the plugin? Did I make some mistake ?

Any help much appreciated!

Thanks!

**Comment by gavinmdouglas** [comment]
Hi @yuyulim,

It looks the version of picrust2 you're using doesn't match the required version of the plugin.

What are the outputs of these commands:

```
which picrust2_pipeline.py
picrust2_pipeline.py --version
```

Best,

Gavin

**Comment by yuyulim** [comment]
Thanks for your reply! @gavinmdouglas 
But I still have some question.
When I runned the commands:
`picrust2_pipeline.py --version`
It showed that it was
`picrust2_pipeline.py 2.1.0-b`
But when I copied the latest version picrust2_pipeline.py 2.3.0-b to the work file folder, the error still existed:
```
Traceback (most recent call last):
  File "/home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/q2cli/commands.py", line 328, in __call__
    results = action(**arguments)
  File "</home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/decorator.py:decorator-gen-477>", line 2, in full_pipeline
  File "/home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/home/jtc/.conda/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/jtc/q2-picrust2-master/q2-picrust2-master/q2_picrust2/_full_pipeline.py", line 70, in full_pipeline
    verbose=highly_verbose)
TypeError: full_pipeline() got an unexpected keyword argument 'processes'

Plugin error from picrust2:

  full_pipeline() got an unexpected keyword argument 'processes'

See above for debug info.
```
The error was same as before. What's wrong is it?

**Comment by gavinmdouglas** [comment]
Hey @yuyulim,

Could you clarify what you mean by copying it to the work file folder? The script needs to be in your $PATH - copying the script to your working directory wouldn't make a difference from the plugin's perspective.


Best,

Gavin

**Comment by yuyulim** [comment]
Oh I copy the picrust2-2.3.0-b verson's picrust2_pipeline.py to replace the picrust2_pipeline.py 2.1.0-b in my path, now the outputs of command `picrust2_pipeline.py --version` is `picrust2_pipeline.py 2.3.0-b`. Maybe I didn't make it clear.

Best ,

yuyulim

**Comment by gavinmdouglas** [comment]
OK I see - copying just that script wont install v2.3.0-b correctly. You would need to uninstall the old version and install the new version entirely with conda in the correct location.


Best,

Gavin

**Comment by yuyulim** [comment]
Thanks for you fast reply!
I download the q2-picrust2 2019.10_0 packages which is described compatible with PICRUSt2 v2.3.0.
The I run the command:
`pip install -e.` 
to uninstall the old version and install the new version
It says:
`Installing collected packages: q2-picrust2
  Attempting uninstall: q2-picrust2
    Found existing installation: q2-picrust2 2019.10
    Uninstalling q2-picrust2-2019.10:
      Successfully uninstalled q2-picrust2-2019.10
  Running setup.py develop for q2-picrust2
Successfully installed q2-picrust2
`
It's very strange that my old version still is q2-picrust2 2019.10_0.
Then I run the command` picrust2_pipeline.py --version ` to make sure it is `picrust2_pipeline.py 2.3.0-b`.
While I run the command :
` jtc@tian-Z10PE-D16-WS:~/q2-picrust2-2019.10_0$ qiime picrust2 full-pipeline \
>    --i-table table.qza \
>    --i-seq rep-seqs.qza \
>    --output-dir q2-picrust2_output \
>    --p-threads 1 \
>    --p-hsp-method pic \
>    --p-max-nsti 2 \`
The error still exist :
`Plugin error from picrust2:

  full_pipeline() got an unexpected keyword argument 'processes'

Debug info has been saved to /tmp/qiime2-q2cli-err-muf520se.log
`
But the traceback disappeared.

Best,

yuyulim

**Comment by gavinmdouglas** [comment]
Hey @yuyulim,

I would try creating a new QIIME 2 environment and re-installing PICRUSt2 in it.


Best,

Gavin
