### ISSUE TITLE
error in KEGG pathway infer

### ISSUE THREAD

**Issue by pinyu99** [picrust/picrust2#156]
Hi, 
i am using PICRSUT2 predict KEGG pathway. 
i use the following command to predict KEGG pathway:
pathway_pipeline.py -i ./pred_metagenome_contrib.tsv -o KEGG_pathway_o --map KEGG_pathways_to_KO.tsv --no_regroup
(the map file was downloaded from https://github.com/picrust/picrust2/tree/master/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv )

The error output by the second command (pathway_pipeline.py) are:
Traceback (most recent call last):
  File "/home/pinyu/.conda/envs/picrust2/bin/pathway_pipeline.py", line 272, in <module>
    main()
  File "/home/pinyu/.conda/envs/picrust2/bin/pathway_pipeline.py", line 210, in main
    verbose=args.verbose)
  File "/home/pinyu/.conda/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 398, in pathway_pipeline
    for sample_id in samples)
  File "/home/pinyu/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/pinyu/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/pinyu/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/pinyu/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/pinyu/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/pinyu/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/pinyu/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/pinyu/.conda/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 898, in contrib_format_pathway_levels
    gap_fill_on)
  File "/home/pinyu/.conda/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 1138, in pathway_abun_and_coverage
    pathway_abun = sum(subset_reaction_abun) / len(subset_reaction_abun)
ZeroDivisionError: division by zero

thank you!

**Comment by gavinmdouglas** [comment]
Hey @pinyu99,

A similar problem was reported here: https://github.com/picrust/picrust2/issues/153

Any chance that the file was downloaded incorrectly as in that case? You can clone the repository to download the file correctly.


Cheers,

Gavin

**Comment by pinyu99** [comment]
thank you for your help!
