### ISSUE TITLE
picrust2 v2.3.0 high memory usage and 'task is too large for send_bytes'

### ISSUE THREAD

**Issue by terrimporter** [picrust/picrust2#157]
I'm trying to transition to picrust2 as I'm not a big fan of closed ref OTU picking.  I've already run this pipeline on a smaller dataset with no issues, but now I'm having trouble with a larger dataset with 114 samples of 16S sequences.

I'm running the command:
picrust2_pipeline.py -s cat.denoised.nonchimeras -i ESV.table -o picrust_out -p 10 --stratified

First time around I got a warning that it was unable to allocate x amt space.  

So instead of running multiple jobs on our little server, I tried just running one job.

Throughout the run, I noticed the metagenome pipeline was using up nearly 40-97% of nearly 50Gb of memory available.  

Now I get:
Error running this command:
pathway_pipeline.py

Standard error of the above failed command:
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/terri/miniconda3/envs/picrust2/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 159, in _feed
    send_bytes(obj_)
  File "/home/terri/miniconda3/envs/picrust2/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/terri/miniconda3/envs/picrust2/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terri/miniconda3/envs/picrust2/bin/pathway_pipeline.py", line 272, in <module>
    main()
  File "/home/terri/miniconda3/envs/picrust2/bin/pathway_pipeline.py", line 187, in main
    verbose=args.verbose)
  File "/home/terri/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 352, in pathway_pipeline
    regroup_mapfile, proc)
  File "/home/terri/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 1180, in regroup_func_ids
    for func_subset in function_chunks)
  File "/home/terri/miniconda3/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/terri/miniconda3/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/terri/miniconda3/envs/picrust2/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/terri/miniconda3/envs/picrust2/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/terri/miniconda3/envs/picrust2/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: The task could not be sent to the workers as it is too large for `send_bytes`.

Any advice?  or do I need to run this on a server with more memory?

Thanks for your advice.

**Comment by gavinmdouglas** [comment]
Hey @terrimporter,

It does sound like you're running into memory issues - switching to a machine with more RAM might be needed to output the data (at least in stratified format - turning that off might lower the memory requirement enough). Another way around this might be to use fewer processors (with the `-p` flag).


Cheers,

Gavin
