### ISSUE TITLE
pytest error in WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by Wang-jianyu** [picrust/picrust2#182]
Hi all,
I am using Windows subsystem for Linux. I use the source code to install the latest version of picrust2 under Ubuntu 20.04.2 LTS. However, there are some problems. Can you take a look and see what the problems are? Thank you for any help.

Wang Jianyu

(picrust2) sword@DESKTOP-RF6GKUJ:/mnt/c/Users/Sword/Desktop/picrust2-2.4.1$ pytest
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.6.13, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /mnt/c/Users/Sword/Desktop/picrust2-2.4.1
plugins: cov-2.12.1
collected 61 items

tests/test_hsp.py ........                                                                                                                                                            [ 13%]
tests/test_metagenome_pipeline.py ...............                                                                                                                                     [ 37%]
tests/test_pathway_pipeline.py ....                                                                                                                                                   [ 44%]
tests/test_place_seqs.py ........F                                                                                                                                                    [ 59%]
tests/test_util.py ....................                                                                                                                                               [ 91%]
tests/test_workflow.py .....                                                                                                                                                          [100%]

========================================================================================= FAILURES ==========================================================================================
____________________________________________________________________ place_seqs_tests.test_run_place_seqs_pipeline_sepp _____________________________________________________________________

self = <tests.test_place_seqs.place_seqs_tests testMethod=test_run_place_seqs_pipeline_sepp>

    def test_run_place_seqs_pipeline_sepp(self):
        '''Basic test of full place seqs pipeline with SEPP. Just run to
           see if any errors occur'''
        with TemporaryDirectory() as temp_dir:
            tmp_tree = path.join(temp_dir, "out.tre")

            place_seqs_pipeline(study_fasta=test_study_seqs,
                                ref_dir=default_ref_dir,
                                placement_tool="sepp",
                                out_tree=tmp_tree,
                                threads=1,
                                out_dir=temp_dir,
                                min_align=0.8,
                                chunk_size=5000,
>                               verbose=True)

tests/test_place_seqs.py:171:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
picrust2/place_seqs.py:97: in place_seqs_pipeline
    print_cmds=verbose)
picrust2/place_seqs.py:451: in run_sepp
    print_stdout=print_cmds, print_stderr=print_cmds)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = ['run_sepp.py', '--tree', '/mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_re.../mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info', '--cpu', ...]
print_command = True, print_stdout = True, print_stderr = True

    def system_call_check(cmd, print_command=False, print_stdout=False,
                          print_stderr=False):
        '''Run system command and throw and error if return is not 0. Input command
        can be a list containing the command or a string.'''

        # Convert command to list if input as string.
        if type(cmd) is str:
            cmd = cmd.split()

        # Print command out if option set.
        if print_command:
            print(" ".join(cmd), file=sys.stderr)

        stdout_log = ""
        stderr_log = ""

        # Write stdout and stderr of command to temporary files.
        # Only output the content of these files if the job fails.
        with TemporaryDirectory() as temp_dir:

            stdout_file = join(temp_dir, "stdout.txt")
            stderr_file = join(temp_dir, "stderr.txt")

            with open(stdout_file, "wb") as stdout_fh, \
                 open(stderr_file, "wb") as stderr_fh:

                return_value = call(cmd, stdout=stdout_fh,
                                    stderr=stderr_fh)

            # Capture stdout and stderr.
            with open(stdout_file, 'r') as stdout_fh:
                stdout_log = stdout_fh.read()

            with open(stderr_file, 'r') as stderr_fh:
                stderr_log = stderr_fh.read()

            # Exit with error if command did not finish successfully.
            if return_value != 0:
                print("\nError running this command:\n" + " ".join(cmd),
                      file=sys.stderr)

                if stdout_log:
                    print("\nStandard output of the above failed command:\n" +
                          stdout_log, file=sys.stderr)

                if stderr_log:
                    print("\nStandard error of the above failed command:\n" +
                          stderr_log, file=sys.stderr)

>               sys.exit(1)
E               SystemExit: 1

picrust2/util.py:263: SystemExit
----------------------------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------------------------

['run_sepp.py', '--tree', '/mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre', '--raxml', '/mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info', '--cpu', '1', '--molecule', 'dna', '--outdir', '/tmp/tmpdl1q3_8w/sepp_out', '-seed', '297834', '--alignment', '/mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna', '--fragment', '/tmp/tmpdl1q3_8w/study_seqs_filtered.fasta']
----------------------------------------------------------------------------------- Captured stderr call ------------------------------------------------------------------------------------
hmmalign --trim --dna --mapali /mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --informat FASTA -o /tmp/tmpdl1q3_8w/query_align.stockholm /mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.hmm /mnt/c/Users/Sword/Desktop/picrust2-2.4.1/tests/test_data/place_seqs/study_seqs_test.fasta

All raw input sequences were the same length (400)

run_sepp.py --tree /mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --raxml /mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info --cpu 1 --molecule dna --outdir /tmp/tmpdl1q3_8w/sepp_out -seed 297834 --alignment /mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --fragment /tmp/tmpdl1q3_8w/study_seqs_filtered.fasta

Error running this command:
run_sepp.py --tree /mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --raxml /mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info --cpu 1 --molecule dna --outdir /tmp/tmpdl1q3_8w/sepp_out -seed 297834 --alignment /mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --fragment /tmp/tmpdl1q3_8w/study_seqs_filtered.fasta

Standard error of the above failed command:
[16:22:10] config.py (line 349):     INFO: Seed number: 297834
[16:22:10] algorithm.py (line 259):     INFO: Reading input alignment: <_io.TextIOWrapper name='/mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna' mode='r' encoding='UTF-8'>
[16:22:10] algorithm.py (line 265):     INFO: Reading input tree: <_io.TextIOWrapper name='/mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre' mode='r' encoding='UTF-8'>
[16:22:11] algorithm.py (line 240):     INFO: Decomposition Sizes are set to alignment: 2000 placement: 2000
[16:22:13] exhaustive.py (line 351):     INFO: Breaking into 16 placement subsets.
[16:22:14] exhaustive.py (line 398):     INFO: Breaking into 16 alignment subsets.
[16:22:14] filemgr.py (line 129):     INFO: Root temp directory built: /tmp/sepp/output.3sfifsez
[16:22:14] exhaustive.py (line 413):     INFO: Breaking each alignment subset into 1 fragment chunks.
[16:22:15] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_0/A_0_0/hmmbuild.input.z3sg37dw.fasta
[16:22:15] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_1/A_1_0/hmmbuild.input._j5yx1ev.fasta
[16:22:15] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_2/A_2_0/hmmbuild.input.9jujkm6w.fasta
[16:22:16] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_3/A_3_0/hmmbuild.input.bm6g8ml6.fasta
[16:22:16] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_4/A_4_0/hmmbuild.input.gk87orqt.fasta
[16:22:17] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_5/A_5_0/hmmbuild.input.un_ii3sd.fasta
[16:22:17] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_6/A_6_0/hmmbuild.input.rjqatr9f.fasta
[16:22:17] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_7/A_7_0/hmmbuild.input.hyxl8glb.fasta
[16:22:18] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_8/A_8_0/hmmbuild.input.uro1xinj.fasta
[16:22:18] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_9/A_9_0/hmmbuild.input.4owps5sh.fasta
[16:22:18] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_10/A_10_0/hmmbuild.input.fl4q5ez3.fasta
[16:22:19] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_11/A_11_0/hmmbuild.input.6xkop3vc.fasta
[16:22:19] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_12/A_12_0/hmmbuild.input.jwgo_k1s.fasta
[16:22:19] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_13/A_13_0/hmmbuild.input.4cjbegti.fasta
[16:22:20] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_14/A_14_0/hmmbuild.input.1_i19f26.fasta
[16:22:20] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.3sfifsez/root/P_15/A_15_0/hmmbuild.input.xirt56dq.fasta
[16:22:20] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_0/A_0_0/hmmbuild.model._y34gwie, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_0/A_0_0/FC_0_0_0/hmmsearch.results.d3izhty1
[16:22:20] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_1/A_1_0/hmmbuild.model.78zllp07, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_1/A_1_0/FC_1_0_0/hmmsearch.results._gg5c8gs
[16:22:20] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_2/A_2_0/hmmbuild.model.5buipklq, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_2/A_2_0/FC_2_0_0/hmmsearch.results.auxgyvcu
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_3/A_3_0/hmmbuild.model.3carrzf2, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_3/A_3_0/FC_3_0_0/hmmsearch.results.nnyb520d
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_4/A_4_0/hmmbuild.model.16yep119, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_4/A_4_0/FC_4_0_0/hmmsearch.results.2scn0yiz
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_5/A_5_0/hmmbuild.model.mqxn4ljn, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_5/A_5_0/FC_5_0_0/hmmsearch.results.tiad9hds
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_6/A_6_0/hmmbuild.model.kotd3tw4, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_6/A_6_0/FC_6_0_0/hmmsearch.results.qvwwijjk
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_7/A_7_0/hmmbuild.model.jt7jv_n1, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_7/A_7_0/FC_7_0_0/hmmsearch.results.vbbjmte1
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_8/A_8_0/hmmbuild.model.wimk1ops, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_8/A_8_0/FC_8_0_0/hmmsearch.results.qf2q7sh9
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_9/A_9_0/hmmbuild.model.nfoyogk_, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_9/A_9_0/FC_9_0_0/hmmsearch.results.75nfee27
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_10/A_10_0/hmmbuild.model.xxraa2bb, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_10/A_10_0/FC_10_0_0/hmmsearch.results.uwns6vze
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_11/A_11_0/hmmbuild.model.f6uk5y8i, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_11/A_11_0/FC_11_0_0/hmmsearch.results.kf9du353
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_12/A_12_0/hmmbuild.model.9bl17sl7, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_12/A_12_0/FC_12_0_0/hmmsearch.results.chn3jwi_
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_13/A_13_0/hmmbuild.model.dn3x9i1z, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_13/A_13_0/FC_13_0_0/hmmsearch.results.0wvnjm52
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_14/A_14_0/hmmbuild.model.x5qhyzit, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_14/A_14_0/FC_14_0_0/hmmsearch.results.sadlkcec
[16:22:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.3sfifsez/root/P_15/A_15_0/hmmbuild.model.yq69hz_k, fragments:/tmp/sepp/output.3sfifsez/fragment_chunks/fragment_chunk_04dsg5ncm.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.3sfifsez/root/P_15/A_15_0/FC_15_0_0/hmmsearch.results.sg2ri1o2
[16:22:21] exhaustive.py (line 81):  WARNING: Fragments [] are not scored against any subset
[16:22:21] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_0.
[16:22:21] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_1.
[16:22:21] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_2.
[16:22:21] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_3.
[16:22:21] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_4.
[16:22:21] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_5.
[16:22:21] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.3sfifsez/root/P_11/A_11_0/hmmbuild.model.f6uk5y8i, fragments:/tmp/sepp/output.3sfifsez/root/P_11/A_11_0/FC_11_0_0/hmmalign.frag.61qeunxj.fasta, trim:False, base_alignment:/tmp/sepp/output.3sfifsez/root/P_11/A_11_0/hmmbuild.input.6xkop3vc.fasta
[16:22:21] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_6.
[16:22:21] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_7.
[16:22:21] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_8.
[16:22:21] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_9.
[16:22:22] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_10.
[16:22:22] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_11.
[16:22:22] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.3sfifsez/root/P_11/A_11_0/FC_11_0_0/hmmalign.results.rbjfc9f_) into base alignment (/tmp/sepp/output.3sfifsez/root/P_11/A_11_0/hmmbuild.input.6xkop3vc.fasta).
[16:22:22] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.3sfifsez/root/P_12/A_12_0/hmmbuild.model.9bl17sl7, fragments:/tmp/sepp/output.3sfifsez/root/P_12/A_12_0/FC_12_0_0/hmmalign.frag.5lt2l5sj.fasta, trim:False, base_alignment:/tmp/sepp/output.3sfifsez/root/P_12/A_12_0/hmmbuild.input.jwgo_k1s.fasta
[16:22:22] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_12.
[16:22:22] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.3sfifsez/root/P_12/A_12_0/FC_12_0_0/hmmalign.results.wx0e3ao7) into base alignment (/tmp/sepp/output.3sfifsez/root/P_12/A_12_0/hmmbuild.input.jwgo_k1s.fasta).
[16:22:22] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_13.
[16:22:22] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_14.
[16:22:22] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_15.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/sword/anaconda3/envs/picrust2/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/sword/anaconda3/envs/picrust2/lib/python3.6/site-packages/sepp/scheduler.py", line 74, in __call__
    return self.run()
  File "/home/sword/anaconda3/envs/picrust2/lib/python3.6/site-packages/sepp/jobs.py", line 154, in run
    if self.read_stderr() else 'No error messages available']))
sepp.scheduler.JobError: The following execution failed:
/home/sword/anaconda3/envs/picrust2/bin/pplacer --out-dir /tmp/sepp/output.3sfifsez/root/P_11 -j 1 -r /tmp/sepp/output.3sfifsez/root/P_11/pplacer.backbone.2b_9cg6k.fasta -s /mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info -t /tmp/sepp/output.3sfifsez/root/P_11/pplacer.tree.dufx6feq.tre --groups 10 /tmp/sepp/output.3sfifsez/root/P_11/pplacer.extended.0.biapencw.fasta
No error messages available
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sword/anaconda3/envs/picrust2/bin/run_sepp.py", line 26, in <module>
    ExhaustiveAlgorithm().run()
  File "/home/sword/anaconda3/envs/picrust2/lib/python3.6/site-packages/sepp/algorithm.py", line 174, in run
    if (not JobPool().wait_for_all_jobs()):
  File "/home/sword/anaconda3/envs/picrust2/lib/python3.6/site-packages/sepp/scheduler.py", line 365, in wait_for_all_jobs
    result.get()
  File "/home/sword/anaconda3/envs/picrust2/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
sepp.scheduler.JobError: The following execution failed:
/home/sword/anaconda3/envs/picrust2/bin/pplacer --out-dir /tmp/sepp/output.3sfifsez/root/P_11 -j 1 -r /tmp/sepp/output.3sfifsez/root/P_11/pplacer.backbone.2b_9cg6k.fasta -s /mnt/c/Users/Sword/Desktop/picrust2-2.4.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info -t /tmp/sepp/output.3sfifsez/root/P_11/pplacer.tree.dufx6feq.tre --groups 10 /tmp/sepp/output.3sfifsez/root/P_11/pplacer.extended.0.biapencw.fasta
No error messages available

================================================================================== short test summary info ==================================================================================
FAILED tests/test_place_seqs.py::place_seqs_tests::test_run_place_seqs_pipeline_sepp - SystemExit: 1

**Comment by gavinmdouglas** [comment]
Hi there,

I think perhaps that SEPP did not install correctly. I have never tried installing it on a Windows subsystem so perhaps there is so some incompatibility? If you have > 16 GB RAM you can try running the default pipeline with EPA-ng for placement rather than SEPP, which based on the tests appears to be working.


Cheers,

Gavin

**Comment by Wang-jianyu** [comment]
Hello Gavin,
In fact, I am a newcomer to python, I tried to reinstall SEPP, but the result is the same as before, but I tried to use chemerin_16S data set(http://kronos.pharmacology.dal.ca/public_files/tutorial_datasets/picrust2_tutorial_files/chemerin_16S.zip), and ran the following line of code, and found that it can be analyzed normally. Does this mean Can I ignore this error?
The code is:
picrust2_pipeline.py -s seqs.fna -i table.biom -o picrust2_out_pipeline -p 1

Thanks again for your help!

Sincerely,

Wang Jianyu

**Comment by gavinmdouglas** [comment]
Yes that should work if SEPP is the only part of the pipeline that is having issues. This is because the default placement tool used is EPA-ng, not SEPP. The downside is that EPA-ng uses much more RAM.

**Comment by Wang-jianyu** [comment]
Thank u! I have gained a lot.

**Comment by Wang-jianyu** [comment]
Thank u! I have gained a lot.
