### ISSUE TITLE
Crash with large datasets

### ISSUE THREAD

**Issue by BostjanMurovec** [picrust/picrust2#193]
Dear PicRust2 developers,

please let me report a discovered PicRust2 2.4.1 issue, where the program crashes when processing large number of OTUs (order of magnitude about 2 million). I have tried to process several such datasets with the same result. With smaller datasets, PicRust2 works okay. I am unable to share the input files, unfortunately.

The screen dump is included below.

Best regards,
Bostjan Murovec

Error running this command:
hsp.py --tree /data/PicRust2/work/out.tre --output /data/PicRust2/work/EC_predicted.tsv.gz --observed_trait_table /biosoft/conda/envs/picrust2_env/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/ec.txt.gz --hsp_method mp --edge_exponent 0.5 --seed 100 --processes 64

Standard error of the above failed command:
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/biosoft/conda/envs/picrust2_env/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 357, in _sendback_result
    exception=exception))
  File "/biosoft/conda/envs/picrust2_env/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 247, in put
    self._writer.send_bytes(obj)
  File "/biosoft/conda/envs/picrust2_env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/biosoft/conda/envs/picrust2_env/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/biosoft/conda/envs/picrust2_env/bin/hsp.py", line 145, in <module>
    main()
  File "/biosoft/conda/envs/picrust2_env/bin/hsp.py", line 136, in main
    verbose=args.verbose)
  File "/biosoft/conda/envs/picrust2_env/lib/python3.6/site-packages/picrust2/wrap_hsp.py", line 72, in castor_hsp_workflow
    for trait_in in file_subsets)
  File "/biosoft/conda/envs/picrust2_env/lib/python3.6/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/biosoft/conda/envs/picrust2_env/lib/python3.6/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/biosoft/conda/envs/picrust2_env/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/biosoft/conda/envs/picrust2_env/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/biosoft/conda/envs/picrust2_env/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by gavinmdouglas** [comment]
Hi @BostjanMurovec,

Thanks for reporting this - you currently have three options to get around this issue, which all involve reducing the number of input OTUs:

* Collapse OTUs into coarser groups based on % identity
* Remove rare OTUs beforehand (i.e., remove those found in fewer than 10% of samples)
* Run OTUs in smaller batches at a time (although an important issue to appreciate here is that there are often minor differences in placement into the reference tree depending on differences in which OTUs are placed together, which means that the predictions will somewhat differ).

If those options don't address the problem then you can try running an alternative metagenome prediction tool like Piphillin or Tax4Fun2 which may be more amenable to datasets this large.


Cheers,

Gavin
