### ISSUE TITLE
Error using custom-map-table

### ISSUE THREAD

**Issue by stvlar** [picrust/picrust2#223]
Hello, I'm trying to add functional descriptions to my function table
Does anyone know what it means and anyway I can solve this?
```

add_descriptions.py -i picrust2_out_pipeline/path_abun_unstrat.tsv.gz --custom_map_table picrust2_out_pipeline/pathway_mapfiles/KEGG_pathways_to_KO.tsv                     -o picrust2_out_pipeline/pathways_out/path_abun_unstrat_descrip.tsv.gz
Traceback (most recent call last):
  File "/home/test/miniconda3/envs/qiime2-2021.2/bin/add_descriptions.py", line 79, in <module>
    main()
  File "/home/test/miniconda3/envs/qiime2-2021.2/bin/add_descriptions.py", line 70, in main
    tab_w_descrip = add_descrip_col(inputfile=args.input, mapfile=mapfile)
  File "/home/test/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/picrust2/util.py", line 430, in add_descrip_col
    low_memory=False, dtype=object)
  File "/home/test/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/test/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/test/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/test/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/pandas/io/parsers.py", line 2198, in read
    values = data.pop(self.index_col[i])
IndexError: list index out of range
```

thanks in advance!

**Comment by gavinmdouglas** [comment]
Hi @stvlar,

Could you show what the top of the pathway mapfile looks like? This error could happen if the file was malformed (sometimes people download the HTML of the file from github rather than the actual file).

Otherwise I would recommend reinstalling the latest version in a new environment!


Cheers,

Gavin
