### ISSUE TITLE
pathway_pipeline.py error

### ISSUE THREAD

**Issue by ksong4** [picrust/picrust2#225]
Hello,

I was running the PICRUST2 (version 2.4.2) to obtain the per ASV contribution in terms of the pathway. I tried both running the picrust2_pipeline.py and running the pipeline individually, neither method works and all stopped on the pathway_pipeline.py
Here are the codes I used for picrust2_pipeline.py:
```
## Full Picrust2 Pipeline
picrust2_pipeline.py \
	-s ${outputFilePath}/PICRUST2_New/${method}/dna-sequences.fasta \
	-i ${outputFilePath}/PICRUST2_New/${method}/${method}_featuretable.biom \
	-o ${outputFilePath}/PICRUST2_New/${method}V4/ \
	-p 1 \
	--per_sequence_contrib \
	--stratified \
	--coverage 
```
The whole pipeline works until the pathway_pipeline step. This failed I run the pathway_pipeline.py separately and obtain the same error as below. Here is a snapshot of the minpath_working folder:
![image](https://user-images.githubusercontent.com/41963331/147893957-87123a35-84ae-44ed-b970-51e58364af91.png)
The minpath_running folder contains the individual sample's report, details, and int txt files, and the minpath_runing_per_seq folder is empty. 
```
pathway_pipeline.py \
	-i ${outputFilePath}/PICRUST2_New/${method}V4/EC_metagenome_out/pred_metagenome_contrib.tsv.gz \
	-o ${outputFilePath}/PICRUST2_New/${method}V4/pathways_out \
	--intermediate ${outputFilePath}/PICRUST2_New/${method}V4/minpath_working \
	--per_sequence_contrib \
	--coverage \
	--per_sequence_abun ${outputFilePath}/PICRUST2_New/${method}V4/EC_metagenome_out/seqtab_norm.tsv.gz \
	--per_sequence_function ${outputFilePath}/PICRUST2_New/${method}V4/EC_predicted.tsv.gz 
```
The error given is listed below and I have imported the pred_metagenom_contrib.tsv.gz, seqtab_norm.tsv.gz, EC_predicted.tsv.gz, and the original FASTA file to R, and the sample id "AABF01000026.18732.20232" is present in all of them. Could you please help me with this? The only thing I could think of is that the biom and FASTA were extracted from the qiime2 feature table and the representative sequence files. I included the dna-sequences.fasta and featuretable.biom files. 
```
Traceback (most recent call last):
  File "/home/ksong4/miniconda3/envs/picrust2/lib/python3.8/site-packages/joblib/parallel.py", line 822, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "/home/ksong4/miniconda3/envs/picrust2/lib/python3.8/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ksong4/miniconda3/envs/picrust2/bin/pathway_pipeline.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/scripts/pathway_pipeline.py", line 272, in <module>
    main()
  File "/home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/scripts/pathway_pipeline.py", line 173, in main
    unstrat_abun_per_seq = pathway_pipeline(
  File "/home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/picrust2/pathway_pipeline.py", line 481, in pathway_pipeline
    path_cov_by_seq = per_sequence_contrib_levels(sequence_abun=per_sequence_abun,
  File "/home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/picrust2/pathway_pipeline.py", line 766, in per_sequence_contrib_levels
    per_seq_raw_out = Parallel(n_jobs=nproc)(delayed(unstrat_pathway_levels)(
  File "/home/ksong4/miniconda3/envs/picrust2/lib/python3.8/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/ksong4/miniconda3/envs/picrust2/lib/python3.8/site-packages/joblib/parallel.py", line 833, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
  File "/home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/picrust2/pathway_pipeline.py", line 768, in <genexpr>
    pred_function[["function", sequence]],
  File "/home1/ksong4/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3461, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home1/ksong4/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home1/ksong4/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['AABF01000026.18732.20232'] not in index"
```
[data01022022.zip](https://github.com/picrust/picrust2/files/7800046/data01022022.zip)

**Comment by gavinmdouglas** [comment]
Hey @ksong4,

I'm unable to regenerate this error. The full pipeline completes when I run the command you provided. How much memory do you have available?


Cheers,

Gavin

**Comment by ksong4** [comment]
Hi, 

I allocated 320 GB of memory for both the full pipeline and the pipeline_pathway.py. I just re-run the full pipeline command and received the same error after 1.5 hours of running and I have attached the error below. When running the full pipeline command, similar to the results from running the pipeline_pathway.py command, the minpath_running folder is done and the minpath_running_per_seq folder is empty and based on the time in which the minpath_running_per_seq folder was created and the script log, the script failed with the attached error generated within a minute of the folder creation. 


```
Warning - 1 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences). These input sequences will not be placed and will be excluded from downstream steps.

This is the set of poorly aligned input sequences to be excluded: 5db1b80faf7b27155c2b85448d6c9f74





3 of 1640 ASVs were above the max NSTI cut-off of 2.0 and were removed from the downstream analyses.

3 of 1640 ASVs were above the max NSTI cut-off of 2.0 and were removed from the downstream analyses.


Error running this command:
pathway_pipeline.py --input /home6/ksong4_tmp/WZ/longMicrobiome/Data//PRJNA290926/ProcessedData/SingleEnd/138//PICRUST2_New/DeNovoV2/EC_metagenome_out/pred_metagenome_unstrat.tsv.gz --out_dir /home6/ksong4_tmp/WZ/longMicrobiome/Data//PRJNA290926/ProcessedData/SingleEnd/138//PICRUST2_New/DeNovoV2/pathways_out --map /home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/picrust2/default_files/pathway_mapfiles/metacyc_path2rxn_struc_filt_pro.txt --intermediate /home6/ksong4_tmp/WZ/longMicrobiome/Data//PRJNA290926/ProcessedData/SingleEnd/138//PICRUST2_New/DeNovoV2/intermediate/pathways --proc 1 --coverage --regroup_map /home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/picrust2/default_files/pathway_mapfiles/ec_level4_to_metacyc_rxn.tsv --per_sequence_contrib --per_sequence_abun /home6/ksong4_tmp/WZ/longMicrobiome/Data//PRJNA290926/ProcessedData/SingleEnd/138//PICRUST2_New/DeNovoV2/EC_metagenome_out/seqtab_norm.tsv.gz --per_sequence_function /home6/ksong4_tmp/WZ/longMicrobiome/Data//PRJNA290926/ProcessedData/SingleEnd/138//PICRUST2_New/DeNovoV2/EC_predicted.tsv.gz

Standard error of the above failed command:
Traceback (most recent call last):
  File "/home/ksong4/miniconda3/envs/picrust2/lib/python3.8/site-packages/joblib/parallel.py", line 822, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "/home/ksong4/miniconda3/envs/picrust2/lib/python3.8/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ksong4/miniconda3/envs/picrust2/bin/pathway_pipeline.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/scripts/pathway_pipeline.py", line 272, in <module>
    main()
  File "/home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/scripts/pathway_pipeline.py", line 173, in main
    unstrat_abun_per_seq = pathway_pipeline(
  File "/home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/picrust2/pathway_pipeline.py", line 481, in pathway_pipeline
    path_cov_by_seq = per_sequence_contrib_levels(sequence_abun=per_sequence_abun,
  File "/home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/picrust2/pathway_pipeline.py", line 766, in per_sequence_contrib_levels
    per_seq_raw_out = Parallel(n_jobs=nproc)(delayed(unstrat_pathway_levels)(
  File "/home/ksong4/miniconda3/envs/picrust2/lib/python3.8/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/ksong4/miniconda3/envs/picrust2/lib/python3.8/site-packages/joblib/parallel.py", line 833, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
  File "/home1/ksong4/InstalledPackages/picrust2/picrust2-2.4.2/picrust2/pathway_pipeline.py", line 768, in <genexpr>
    pred_function[["function", sequence]],
  File "/home1/ksong4/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3461, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home1/ksong4/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home1/ksong4/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['000fb62885c2a447b61a85ea13f5d76e'] not in index"
```

**Comment by gavinmdouglas** [comment]
Hey @ksong4,

Very sorry that I forgot to respond to this - it totally fell off my plate. Did you resolve it?

Using the unstrat table with the --per_sequence_contrib option is correct (as the additional tables are pointed to when that option is used).


Cheers,

Gavin

**Comment by ksong4** [comment]
Hi @gavinmdouglas,

Yes, thank you so much for helping out! 

Best,
