### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by huizhen-yan** [picrust/picrust2#238]
When I run picrust2_pipeline.py , I got an error. 
Here is the code and error message. Can you help me?? 

(picrust2) yanhz@yanhz:~/Documents/tools/lhy$ picrust2_pipeline.py -s en26000.fasta -i otu26000.txt -o picrust2_out26000

Error running this command:
metagenome_pipeline.py --input otu26000.txt --function picrust2_out26000/EC_predicted.tsv.gz --min_reads 1 --min_samples 1 --out_dir picrust2_out26000/EC_metagenome_out --max_nsti 2.0 --marker picrust2_out26000/marker_predicted_and_nsti.tsv.gz

Standard error of the above failed command:
46 of 20709 ASVs were above the max NSTI cut-off of 2.0 and were removed from the downstream analyses.
Traceback (most recent call last):
  File "/home/yanhz/miniconda2/envs/picrust2/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
  File "/home/yanhz/miniconda2/envs/picrust2/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/home/yanhz/miniconda2/envs/picrust2/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 69, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for /: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanhz/miniconda2/envs/picrust2/bin/metagenome_pipeline.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/yanhz/Documents/tools/picrust2/picrust2-2.4.2/scripts/metagenome_pipeline.py", line 122, in <module>
    main()
  File "/home/yanhz/Documents/tools/picrust2/picrust2-2.4.2/scripts/metagenome_pipeline.py", line 94, in main
    strat_pred, unstrat_pred = run_metagenome_pipeline(
  File "/home/yanhz/Documents/tools/picrust2/picrust2-2.4.2/picrust2/metagenome_pipeline.py", line 72, in run_metagenome_pipeline
    study_seq_counts = norm_by_marker_copies(input_seq_counts=study_seq_counts,
  File "/home/yanhz/Documents/tools/picrust2/picrust2-2.4.2/picrust2/metagenome_pipeline.py", line 259, in norm_by_marker_copies
    input_seq_counts = input_seq_counts.div(input_marker_num.loc[
  File "/home/yanhz/miniconda2/envs/picrust2/lib/python3.8/site-packages/pandas/core/ops/__init__.py", line 438, in f
    new_data = self._combine_frame(other, na_op, fill_value)
  File "/home/yanhz/miniconda2/envs/picrust2/lib/python3.8/site-packages/pandas/core/frame.py", line 7037, in _combine_frame
    new_data = self._dispatch_frame_op(other, _arith_op)
  File "/home/yanhz/miniconda2/envs/picrust2/lib/python3.8/site-packages/pandas/core/frame.py", line 6979, in _dispatch_frame_op
    bm = self._mgr.operate_blockwise(
  File "/home/yanhz/miniconda2/envs/picrust2/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1409, in operate_blockwise
    return operate_blockwise(self, other, array_op)
  File "/home/yanhz/miniconda2/envs/picrust2/lib/python3.8/site-packages/pandas/core/internals/ops.py", line 63, in operate_blockwise
    res_values = array_op(lvals, rvals)
  File "/home/yanhz/miniconda2/envs/picrust2/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 222, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "/home/yanhz/miniconda2/envs/picrust2/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 170, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
  File "/home/yanhz/miniconda2/envs/picrust2/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 108, in _masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
TypeError: unsupported operand type(s) for /: 'str' and 'int'

(picrust2) yanhz@yanhz:~/Documents/tools/lhy$

**Comment by gavinmdouglas** [comment]
Hi @huizhen-yan,

It looks like the columns in your abundance table are being interpreted as strings rather than numbers. If you look at the input OTU table is there an obvious reason why that would be the case? If nothing is striking feel free to send it to me at
![gmail_screenshot](https://user-images.githubusercontent.com/12489683/155770893-d3542ef1-ea74-4a9c-b834-981828fab784.jpg) and I can take a look.


Cheers,

Gavin

**Comment by huizhen-yan** [comment]
Thank you very much for your reminder, the first cell of the abundance table contains #, so I delete this cell and run "picrust2_pipeline.py -s rep.fasta -i otu.txt -o picrust_out", then I got the following warning:
Maybe this doesn't affect the result.

/home/yanhz/Documents/tools/picrust2/picrust2-2.4.2/picrust2/pathway_pipeline.py:1243: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(new_subset)
/home/yanhz/Documents/tools/picrust2/picrust2-2.4.2/picrust2/pathway_pipeline.py:1243: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(new_subset)
/home/yanhz/Documents/tools/picrust2/picrust2-2.4.2/picrust2/pathway_pipeline.py:1243: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(new_subset)
/home/yanhz/Documents/tools/picrust2/picrust2-2.4.2/picrust2/pathway_pipeline.py:1243: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(new_subset)
/home/yanhz/Documents/tools/picrust2/picrust2-2.4.2/picrust2/pathway_pipeline.py:1243: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(new_subset)

(picrust2) yanhz@yanhz:~/Documents/tools$

**Comment by gavinmdouglas** [comment]
You can disregard that, as it is just a warning about how a dependency will change in the future.
