### ISSUE TITLE
Picrust2 Pytest Issue

### ISSUE THREAD

**Issue by Lor-AM** [picrust/picrust2#246]
I installed Picrust2.4.2 on my linux system and after following the steps mentioned on  https://huttenhower.sph.harvard.edu/picrust/ . OZn running pytest I am getting 5 errors picrust2/util.py:263: SystemExit
------------------------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------------------------

Error running this command:
picrust2_pipeline.py -s /home/u966070/picrust2-2.4.2/tests/test_data/place_seqs/study_seqs_test.fasta -i /home/u966070/picrust2-2.4.2/tests/test_data/workflow/workflow_seq_abun.tsv.gz -o /tmp/tmpxak5r02m/pipeline_out -r /home/u966070/picrust2-2.4.2/tests/test_data/place_seqs/img_centroid_16S_aligned_head30 -p 1 --custom_trait_tables /home/u966070/picrust2-2.4.2/tests/test_data/workflow/workflow_known_traits.tsv.gz --marker_gene_table /home/u966070/picrust2-2.4.2/tests/test_data/workflow/workflow_known_marker.tsv.gz --reaction_func /home/u966070/picrust2-2.4.2/tests/test_data/workflow/workflow_known_traits.tsv.gz --max_nsti 1.9 --min_reads 2 --min_samples 2 --skip_minpath --no_gap_fill --coverage --remove_intermediate --stratified --per_sequence_contrib --skip_norm --verbose

Standard error of the above failed command:
Traceback (most recent call last):
  File "/home/u966070/anaconda3/envs/picrust2/bin/picrust2_pipeline.py", line 4, in <module>
    __import__('pkg_resources').require('PICRUSt2==2.4.2')
  File "/home/u966070/anaconda3/envs/picrust2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/home/u966070/anaconda3/envs/picrust2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/u966070/anaconda3/envs/picrust2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/u966070/anaconda3/envs/picrust2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/u966070/anaconda3/envs/picrust2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/u966070/anaconda3/envs/picrust2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cython' distribution was not found and is required by biom-format

======================================================================================= warnings summary =======================================================================================
tests/test_pathway_pipeline.py: 54 warnings
  /home/u966070/picrust2-2.4.2/picrust2/pathway_pipeline.py:1243: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
    new_df = new_df.append(new_subset)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================================================================================== short test summary info ====================================================================================
FAILED tests/test_workflow.py::workflow_test::test_full_pipeline_tsv - SystemExit: 1
FAILED tests/test_workflow.py::workflow_test::test_help_calls - SystemExit: 1
FAILED tests/test_workflow.py::workflow_test::test_picrust2_pipeline_script - SystemExit: 1
FAILED tests/test_workflow.py::workflow_test::test_picrust2_pipeline_script_per_seq_contrib_strat - SystemExit: 1
FAILED tests/test_workflow.py::workflow_test::test_picrust2_pipeline_script_per_seq_contrib_strat_skip_norm - SystemExit: 1

Could you tell me how to resolve this

**Comment by gavinmdouglas** [comment]
Hi @Lor-AM,

Did you install from source or follow the conda install steps? I would recommend you install with the conda option if you did not. 

It seems like this is a permission error to write to tmp, which is odd... Can you confirm that you have permission to write to the tmp directory for other tasks?


Cheers,

Gavin

**Comment by Lor-AM** [comment]
Hi, I was installing from source. When I was trying to install from conda the process seemed stuck for many hours . However, I was able to get the issue. While running the command pip install --editable some packages such as cython 0.29 etc were not getting installed . I installed them separately in the picrust2 environment and then tested with pytest. Its working as of now. Thank you

**Comment by gavinmdouglas** [comment]
Good to hear!
