### ISSUE TITLE
May seem like a silly question, but how do I access the output files?

### ISSUE THREAD

**Issue by chuynh96** [picrust/picrust2#256]
Hello,

As the title asks, how do I find the output files after running picrust2_pipeline.py? I'm honestly not even sure if it actually worked.
I ran the following: 
picrust2_pipeline.py -s Colorectal1.fasta -i Colorectal1OTU.biom -o picrust2_out_pipeline -p 1
And this was returned:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/myenv/envs/picrust2/bin/picrust2_pipeline.py", line 280, in <module>
    main()
  File "/opt/anaconda3/envs/myenv/envs/picrust2/bin/picrust2_pipeline.py", line 242, in main
    func_outfiles, pathway_outfiles = full_pipeline(study_fasta=args.study_fasta,
  File "/opt/anaconda3/envs/myenv/envs/picrust2/lib/python3.8/site-packages/picrust2/pipeline.py", line 120, in full_pipeline
    check_overlapping_seqs(study_fasta, input_table, verbose)
  File "/opt/anaconda3/envs/myenv/envs/picrust2/lib/python3.8/site-packages/picrust2/pipeline.py", line 365, in check_overlapping_seqs
    FASTA_ASVs = set(read_fasta(in_seq).keys())
  File "/opt/anaconda3/envs/myenv/envs/picrust2/lib/python3.8/site-packages/picrust2/util.py", line 68, in read_fasta
    seq[name] += line
KeyError: None
Any help would be greatly appreciated! Thank you!!

Mai

**Comment by gavinmdouglas** [comment]
Hi there,

This error means that it wasn't able to read in your input FASTA file. Would you mind posting the first few lines of the file?


Thanks,

Gavin
