### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'hmmalign': 'hmmalign'

### ISSUE THREAD

**Issue by george-weingart** [picrust/picrust2#260]
Hello,
We just installed Picrust2 and I am trying to run a sample workflow using the following job:
===================================================================
#!/bin/bash
iDir="/galaxy-central/tools/galaxy-upgrade/galaxy_picrust2/test_data/workflow"
sDir="/galaxy-central/tools/galaxy-upgrade/galaxy_picrust2/test_data"
picrust2_pipeline.py -s $sDir/study_seqs_test.fasta -i $iDir/workflow_seq_abun.biom -o picrust2_out --processes 10 --stratified --per_sequence_contrib
=====================================================================================

When I run it, I get the following error:
====================================================================================
Error running this command:
place_seqs.py --study_fasta /galaxy-central/tools/galaxy-upgrade/galaxy_picrust2/test_data/study_seqs_test.fasta --ref_dir /galaxy-central/tools/picrust2/picrust2/default_files/prokaryotic/pro_ref --out_tree picrust2_out/out.tre --processes 10 --intermediate picrust2_out/intermediate/place_seqs --min_align 0.8 --chunk_size 5000 --placement_tool epa-ng

Standard error of the above failed command:
Traceback (most recent call last):
  File "/galaxy_venv/bin/place_seqs.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/galaxy-central/tools/picrust2/scripts/place_seqs.py", line 111, in <module>
    main()
  File "/galaxy-central/tools/picrust2/scripts/place_seqs.py", line 95, in main
    verbose=args.verbose)
  File "/galaxy-central/tools/picrust2/picrust2/place_seqs.py", line 50, in place_seqs_pipeline
    print_stderr=verbose)
  File "/galaxy-central/tools/picrust2/picrust2/util.py", line 241, in system_call_check
    stderr=stderr_fh)
  File "/tool_deps/_conda/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/tool_deps/_conda/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/tool_deps/_conda/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hmmalign': 'hmmalign'

==============================================================================

Can you help us figure the error ?
Thanks !
George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

**Comment by gavinmdouglas** [comment]
It looks like the key error is 
```

**Comment by george-weingart** [comment]
Thanks Gavin !
