### ISSUE TITLE
Standard error of the above failed command

### ISSUE THREAD

**Issue by TKsh6** [picrust/picrust2#270]
Command: `picrust2_pipeline.py -s 1380F_1510R_seq/PW_dna-sequences.fasta -i 1380F_1510R_table/PW_feature_table.txt -o res`
I got this error:
```
Error running this command:
place_seqs.py --study_fasta 1380F_1510R_seq/PW_dna-sequences.fasta --ref_dir /beegfs/home/syl/anaconda3/envs/picrust2/lib/python3.10/site-packages/picrust2/default_files/prokaryotic/pro_ref --out_tree res/out.tre --processes 1 --intermediate res/intermediate/place_seqs --min_align 0.8 --chunk_size 5000 --placement_tool epa-ng

Standard error of the above failed command:
Warning - 31415 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences). These input sequences will not be placed and will be excluded from downstream steps.

```
```
Traceback (most recent call last):
  File "/beegfs/home/syl/anaconda3/envs/picrust2/bin/place_seqs.py", line 111, in <module>
    main()
  File "/beegfs/home/syl/anaconda3/envs/picrust2/bin/place_seqs.py", line 87, in main
    place_seqs_pipeline(study_fasta=args.study_fasta,
  File "/beegfs/home/syl/anaconda3/envs/picrust2/lib/python3.10/site-packages/picrust2/place_seqs.py", line 75, in place_seqs_pipeline
    run_epa_ng(tree=tree,
  File "/beegfs/home/syl/anaconda3/envs/picrust2/lib/python3.10/site-packages/picrust2/place_seqs.py", line 187, in run_epa_ng
    system_call_check(epa_ng_command, print_command=print_cmds,
  File "/beegfs/home/syl/anaconda3/envs/picrust2/lib/python3.10/site-packages/picrust2/util.py", line 240, in system_call_check
    return_value = call(cmd, stdout=stdout_fh,
  File "/beegfs/home/syl/anaconda3/envs/picrust2/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/beegfs/home/syl/anaconda3/envs/picrust2/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/beegfs/home/syl/anaconda3/envs/picrust2/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'epa-ng'
```
So how can I do to deal with it?

**Comment by gavinmdouglas** [comment]
Hi there,

The main error is `FileNotFoundError: [Errno 2] No such file or directory: 'epa-ng'`

This means that epa-ng is not found in your path (which means that the conda envrionment was not installed correctly). I would try re-installing.

The warning is that >30,000 sequences couldn't be aligned though, which is worrisome. How many ASVs / OTUs are you inputting?


Gavin

**Comment by TKsh6** [comment]
I have tried re-installing and it works. In this task, 36954 sequence were aliged but 31415 input sequences aligned poorly to reference sequences. Cause these OTUs are from Micro-eukaryotes which were extracted from the samples , so is it all right?

**Comment by gavinmdouglas** [comment]
Ok great to hear. Yes the default database is for 16S rRNA genes (i.e., prokaryotic data), so that makes sense. If all the OTUs are eukaryotic (18S?) then this pipeline is not appropriate.

**Comment by TKsh6** [comment]
Thank you very much! Other OTUs from bacteria have been successfully processed through this pipeline, and I'll find another way to process OTUs(18s).
TK
