### ISSUE TITLE
Error in runing picrust 2

### ISSUE THREAD

**Issue by linki11** [picrust/picrust2#278]
Hi, I am new. I got this error when I was running piecrust 2.. Thank you so much for your kind assistance!!
Error running this command:
metagenome_pipeline.py --input /Users/linkilam/Desktop/picrust/otu_table.absolute.txt --function /Users/linkilam/Desktop/picrust/picrust2_out_pipeline/EC_predicted.tsv.gz --min_reads 1 --min_samples 1 --out_dir /Users/linkilam/Desktop/picrust/picrust2_out_pipeline/EC_metagenome_out --max_nsti 2.0 --marker /Users/linkilam/Desktop/picrust/picrust2_out_pipeline/marker_predicted_and_nsti.tsv.gz

Standard error of the above failed command:
240 of 13484 ASVs were above the max NSTI cut-off of 2.0 and were removed from the downstream analyses.
Traceback (most recent call last):
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 143, in na_arithmetic_op
    result = expressions.evaluate(op, left, right)
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 233, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for /: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/bin/metagenome_pipeline.py", line 122, in <module>
    main()
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/bin/metagenome_pipeline.py", line 104, in main
    skip_norm=args.skip_norm)
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/metagenome_pipeline.py", line 74, in run_metagenome_pipeline
    norm_filename=norm_output)
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/metagenome_pipeline.py", line 262, in norm_by_marker_copies
    axis="index")
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 655, in f
    new_data = self._combine_frame(other, na_op, fill_value)
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/core/frame.py", line 5870, in _combine_frame
    new_data = ops.dispatch_to_series(self, other, _arith_op)
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 275, in dispatch_to_series
    bm = left._mgr.operate_blockwise(right._mgr, array_op)
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 367, in operate_blockwise
    return operate_blockwise(self, other, array_op)
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/core/internals/ops.py", line 38, in operate_blockwise
    res_values = array_op(lvals, rvals)
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 190, in arithmetic_op
    res_values = na_arithmetic_op(lvalues, rvalues, op)
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 150, in na_arithmetic_op
    result = masked_arith_op(left, right, op)
  File "/Users/linkilam/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 92, in masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
TypeError: unsupported operand type(s) for /: 'str' and 'int'

**Comment by gavinmdouglas** [comment]
Hi there, this sounds similar to the problem reported here: https://github.com/picrust/picrust2/issues/238

If you take a look at the abundance table, is there any reason why the abundances might be interpreted as strings? In the example I linked to there was a "#" character at the beginning that was causing problems.


Thanks,

Gavin

**Comment by linki11** [comment]
Yes. I deleted "#" in OTU table. It works. thank you so much!
