### ISSUE TITLE
metagenome pipeline not working: 

### ISSUE THREAD

**Issue by arghya1611** [picrust/picrust2#29]
Hi
I am getting this error message:

metagenome_pipeline.py -i FM.biom -m 16S_predicted.tsv -f EC_predicted.tsv -p 10 -o metagenome 
Traceback (most recent call last):
  File "/home/hh750/anaconda2/envs/picrust2-dev/bin/metagenome_pipeline.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/hh750/Apps/picrust2/scripts/metagenome_pipeline.py", line 82, in <module>
    main()
  File "/home/hh750/Apps/picrust2/scripts/metagenome_pipeline.py", line 70, in main
    output_normfile=True)
  File "/home/hh750/Apps/picrust2/picrust2/metagenome_pipeline.py", line 59, in run_metagenome_pipeline
    pred_marker)
  File "/home/hh750/Apps/picrust2/picrust2/util.py", line 246, in three_df_index_overlap_sort
    "input files.")
ValueError: No sequence ids overlap between all three of the input files.

My input files are from qiime 2. I have checked the rep seq file which was used in the placement step and the .biom file along with the 16S and EC predicted files. The sequence IDs are there. What is going wrong?Please help.

**Comment by gavinmdouglas** [comment]
Hey there,

What version of PICRUSt2 are you using? It's difficult to troubleshoot the problem from this message alone - would you mind sending me your files privately at gavinmdouglas@gmail.com ?

**Comment by gavinmdouglas** [comment]
Closed due to inactivity - let me know if this is still an issue!
