### ISSUE TITLE
q2-picrust2 Tutorial error_ "pro_ref.raxml_info" could not be found.

### ISSUE THREAD

**Issue by gomong** [picrust/picrust2#291]
Hi. It is my first using PICRUSt, and I have problems while trying PICRUSt tutorial.

Basically, my computer (64-bit) has 8GB RAM and I'm working on Ubuntu v.20
So, I would like to utilize SEPP rather than EPA/NG.

I have got some troubles in running the full PICRUSt2 pipeline with the below command.
`qiime picrust2 full-pipeline \
   --i-table mammal_biom.qza \
   --i-seq mammal_seqs.qza \
   --output-dir q2-picrust2_output \
   --p-placement-tool sepp \
   --p-threads 1 \
   --p-hsp-method pic \
   --p-max-nsti 2 \
   --verbose`

The message said;
```
The following expected file(s) could not be found:
/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info

Error - missing at least one of the four reference files in this specified directory: /home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref

```
So, to solve this problem, I downloaded the folder named 'pro_ref' from..
https://github.com/picrust/picrust2/tree/master/picrust2/default_files/prokaryotic/pro_ref
into the above specified directory. (I apologize if the attemp like this is disallowed..)

However, it didn't work, consquentially.
I got the messege like below: 
```
(qiime2-2019.10) kys123@DESKTOP-7S93C42:~/q2-picrust2_tutorial$ qiime picrust2 full-pipeline \
  --i-ta>    --i-table mammal_biom.qza \
  --i-se>    --i-seq mammal_seqs.qza \
>    --output-dir q2-picrust2_output \
p-placem>    --p-placement-tool sepp \
>    --p-threads 1 \
>    --p-hsp-method pic \
>    --p-max-nsti 2 \
>    --verbose

Error running this command:
place_seqs.py --study_fasta /tmp/tmppk45c0pg/seqs.fna --ref_dir /home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref --out_tree /tmp/tmppk45c0pg/picrust2_out/out.tre --processes 1 --intermediate /tmp/tmppk45c0pg/picrust2_out/intermediate/place_seqs --min_align 0.8 --chunk_size 5000 --placement_tool sepp

Standard output of the above failed command:
['run_sepp.py', '--tree', '/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre', '--raxml', '/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info', '--cpu', '1', '--molecule', 'dna', '--outdir', '/tmp/tmppk45c0pg/picrust2_out/intermediate/place_seqs/sepp_out', '-seed', '297834', '--alignment', '/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna', '--fragment', '/tmp/tmppk45c0pg/picrust2_out/intermediate/place_seqs/study_seqs_filtered.fasta']


Standard error of the above failed command:

Error running this command:
run_sepp.py --tree /home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --raxml /home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info --cpu 1 --molecule dna --outdir /tmp/tmppk45c0pg/picrust2_out/intermediate/place_seqs/sepp_out -seed 297834 --alignment /home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --fragment /tmp/tmppk45c0pg/picrust2_out/intermediate/place_seqs/study_seqs_filtered.fasta

Standard error of the above failed command:
[16:54:59] config.py (line 349):     INFO: Seed number: 297834
[16:54:59] algorithm.py (line 259):     INFO: Reading input alignment: <_io.TextIOWrapper name='/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna' mode='r' encoding='UTF-8'>
[16:55:00] algorithm.py (line 265):     INFO: Reading input tree: <_io.TextIOWrapper name='/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre' mode='r' encoding='UTF-8'>
[16:55:01] algorithm.py (line 240):     INFO: Decomposition Sizes are set to alignment: 2000 placement: 2000
[16:55:03] exhaustive.py (line 351):     INFO: Breaking into 16 placement subsets.
[16:55:05] exhaustive.py (line 398):     INFO: Breaking into 16 alignment subsets.
[16:55:05] filemgr.py (line 129):     INFO: Root temp directory built: /tmp/sepp/output.av1ips1c
[16:55:05] exhaustive.py (line 413):     INFO: Breaking each alignment subset into 1 fragment chunks.
[16:55:05] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_0/A_0_0/hmmbuild.input.pt9kj47m.fasta
[16:55:06] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_1/A_1_0/hmmbuild.input.e0exlmcd.fasta
[16:55:06] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_2/A_2_0/hmmbuild.input.qjk_friy.fasta
[16:55:06] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_3/A_3_0/hmmbuild.input.hlhdzgnm.fasta
[16:55:06] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_4/A_4_0/hmmbuild.input.bahyfsxy.fasta
[16:55:07] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_5/A_5_0/hmmbuild.input.15fykeu3.fasta
[16:55:07] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_6/A_6_0/hmmbuild.input.7m4c5zvy.fasta
[16:55:07] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_7/A_7_0/hmmbuild.input.v1s3mc0r.fasta
[16:55:08] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_8/A_8_0/hmmbuild.input.i1agn17g.fasta
[16:55:08] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_9/A_9_0/hmmbuild.input.mckbzovg.fasta
[16:55:08] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_10/A_10_0/hmmbuild.input.u8ygg38u.fasta
[16:55:08] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_11/A_11_0/hmmbuild.input.s50ckgir.fasta
[16:55:09] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_12/A_12_0/hmmbuild.input.6urnt5pj.fasta
[16:55:09] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_13/A_13_0/hmmbuild.input.jr8s_erv.fasta
[16:55:09] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_14/A_14_0/hmmbuild.input.z6mjqka8.fasta
[16:55:09] jobs.py (line 132):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.av1ips1c/root/P_15/A_15_0/hmmbuild.input.3cj6ii37.fasta
[16:55:13] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_0/A_0_0/hmmbuild.model.mmm4lxa_, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_0/A_0_0/FC_0_0_0/hmmsearch.results.mwquz7gk
[16:55:17] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_1/A_1_0/hmmbuild.model.5yf6kl7o, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_1/A_1_0/FC_1_0_0/hmmsearch.results.w6wdhwq6
[16:55:21] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_2/A_2_0/hmmbuild.model.etgeb5xz, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_2/A_2_0/FC_2_0_0/hmmsearch.results.avbpj3_i
[16:55:25] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_3/A_3_0/hmmbuild.model.c1tsz67i, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_3/A_3_0/FC_3_0_0/hmmsearch.results.nkhjru84
[16:55:29] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_4/A_4_0/hmmbuild.model.cztgtj1_, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_4/A_4_0/FC_4_0_0/hmmsearch.results.nhwm8s6x
[16:55:34] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_5/A_5_0/hmmbuild.model._ax3e__z, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_5/A_5_0/FC_5_0_0/hmmsearch.results.qp0fhizh
[16:55:38] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_6/A_6_0/hmmbuild.model.l2z_z2eq, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_6/A_6_0/FC_6_0_0/hmmsearch.results.4_fpuvky
[16:55:41] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_7/A_7_0/hmmbuild.model.a91eq2q9, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_7/A_7_0/FC_7_0_0/hmmsearch.results.7fi_y6qh
[16:55:45] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_8/A_8_0/hmmbuild.model.8y3ra0kb, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_8/A_8_0/FC_8_0_0/hmmsearch.results.h0sbn6p0
[16:55:49] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_9/A_9_0/hmmbuild.model.2ez4uw4n, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_9/A_9_0/FC_9_0_0/hmmsearch.results.oay4ecyj
[16:55:53] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_10/A_10_0/hmmbuild.model.9l6hci37, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_10/A_10_0/FC_10_0_0/hmmsearch.results.3fq571le
[16:55:57] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_11/A_11_0/hmmbuild.model.ho5gzfgo, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_11/A_11_0/FC_11_0_0/hmmsearch.results.wioyzurr
[16:56:01] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_12/A_12_0/hmmbuild.model.cqhiogzg, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_12/A_12_0/FC_12_0_0/hmmsearch.results._kknxizu
[16:56:05] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_13/A_13_0/hmmbuild.model.2d3s2u8f, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_13/A_13_0/FC_13_0_0/hmmsearch.results.vuv75wiv
[16:56:09] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_14/A_14_0/hmmbuild.model.el_nevt_, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_14/A_14_0/FC_14_0_0/hmmsearch.results.3qg458uh
[16:56:13] jobs.py (line 132):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.av1ips1c/root/P_15/A_15_0/hmmbuild.model.dv8w83cx, fragments:/tmp/sepp/output.av1ips1c/fragment_chunks/fragment_chunk_06qzrmh1l.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.av1ips1c/root/P_15/A_15_0/FC_15_0_0/hmmsearch.results.sfemnu3f
[16:56:13] exhaustive.py (line 81):  WARNING: Fragments [] are not scored against any subset
[16:56:13] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_0.
[16:56:13] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_1/A_1_0/hmmbuild.model.5yf6kl7o, fragments:/tmp/sepp/output.av1ips1c/root/P_1/A_1_0/FC_1_0_0/hmmalign.frag.07pjgk1k.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_1/A_1_0/hmmbuild.input.e0exlmcd.fasta
[16:56:13] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_1.
[16:56:13] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_1/A_1_0/FC_1_0_0/hmmalign.results.oxhkd0lb) into base alignment (/tmp/sepp/output.av1ips1c/root/P_1/A_1_0/hmmbuild.input.e0exlmcd.fasta).
[16:56:13] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_2/A_2_0/hmmbuild.model.etgeb5xz, fragments:/tmp/sepp/output.av1ips1c/root/P_2/A_2_0/FC_2_0_0/hmmalign.frag.tix4gsb7.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_2/A_2_0/hmmbuild.input.qjk_friy.fasta
[16:56:13] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_2.
[16:56:13] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_2/A_2_0/FC_2_0_0/hmmalign.results.xlehg832) into base alignment (/tmp/sepp/output.av1ips1c/root/P_2/A_2_0/hmmbuild.input.qjk_friy.fasta).
[16:56:13] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_3/A_3_0/hmmbuild.model.c1tsz67i, fragments:/tmp/sepp/output.av1ips1c/root/P_3/A_3_0/FC_3_0_0/hmmalign.frag.oiqm4q97.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_3/A_3_0/hmmbuild.input.hlhdzgnm.fasta
[16:56:13] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_3.
[16:56:13] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_3/A_3_0/FC_3_0_0/hmmalign.results.ljy4xha4) into base alignment (/tmp/sepp/output.av1ips1c/root/P_3/A_3_0/hmmbuild.input.hlhdzgnm.fasta).
[16:56:13] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_4/A_4_0/hmmbuild.model.cztgtj1_, fragments:/tmp/sepp/output.av1ips1c/root/P_4/A_4_0/FC_4_0_0/hmmalign.frag.6kwz3g0e.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_4/A_4_0/hmmbuild.input.bahyfsxy.fasta
[16:56:13] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_4.
[16:56:13] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_4/A_4_0/FC_4_0_0/hmmalign.results.pv1jrtg1) into base alignment (/tmp/sepp/output.av1ips1c/root/P_4/A_4_0/hmmbuild.input.bahyfsxy.fasta).
[16:56:13] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_5/A_5_0/hmmbuild.model._ax3e__z, fragments:/tmp/sepp/output.av1ips1c/root/P_5/A_5_0/FC_5_0_0/hmmalign.frag.o7z4kisz.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_5/A_5_0/hmmbuild.input.15fykeu3.fasta
[16:56:13] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_5.
[16:56:13] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_5/A_5_0/FC_5_0_0/hmmalign.results.bjerga_h) into base alignment (/tmp/sepp/output.av1ips1c/root/P_5/A_5_0/hmmbuild.input.15fykeu3.fasta).
[16:56:14] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_6/A_6_0/hmmbuild.model.l2z_z2eq, fragments:/tmp/sepp/output.av1ips1c/root/P_6/A_6_0/FC_6_0_0/hmmalign.frag.w5_au94i.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_6/A_6_0/hmmbuild.input.7m4c5zvy.fasta
[16:56:14] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_6.
[16:56:14] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_6/A_6_0/FC_6_0_0/hmmalign.results.k52c4k23) into base alignment (/tmp/sepp/output.av1ips1c/root/P_6/A_6_0/hmmbuild.input.7m4c5zvy.fasta).
[16:56:14] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_7/A_7_0/hmmbuild.model.a91eq2q9, fragments:/tmp/sepp/output.av1ips1c/root/P_7/A_7_0/FC_7_0_0/hmmalign.frag.ywcfvjj7.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_7/A_7_0/hmmbuild.input.v1s3mc0r.fasta
[16:56:15] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_10/A_10_0/hmmbuild.model.9l6hci37, fragments:/tmp/sepp/output.av1ips1c/root/P_10/A_10_0/FC_10_0_0/hmmalign.frag.npard5nv.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_10/A_10_0/hmmbuild.input.u8ygg38u.fasta
[16:56:15] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_7.
[16:56:15] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_7/A_7_0/FC_7_0_0/hmmalign.results.46xjblmc) into base alignment (/tmp/sepp/output.av1ips1c/root/P_7/A_7_0/hmmbuild.input.v1s3mc0r.fasta).
[16:56:16] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_8.
[16:56:17] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_9.
[16:56:18] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_10.
[16:56:18] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_10/A_10_0/FC_10_0_0/hmmalign.results.dq6y2l7q) into base alignment (/tmp/sepp/output.av1ips1c/root/P_10/A_10_0/hmmbuild.input.u8ygg38u.fasta).
[16:56:22] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_11/A_11_0/hmmbuild.model.ho5gzfgo, fragments:/tmp/sepp/output.av1ips1c/root/P_11/A_11_0/FC_11_0_0/hmmalign.frag.d1j8u8vi.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_11/A_11_0/hmmbuild.input.s50ckgir.fasta
[16:56:22] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_11.
[16:56:22] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_11/A_11_0/FC_11_0_0/hmmalign.results.74ccx1rw) into base alignment (/tmp/sepp/output.av1ips1c/root/P_11/A_11_0/hmmbuild.input.s50ckgir.fasta).
[16:56:23] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_12/A_12_0/hmmbuild.model.cqhiogzg, fragments:/tmp/sepp/output.av1ips1c/root/P_12/A_12_0/FC_12_0_0/hmmalign.frag.nx03kilq.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_12/A_12_0/hmmbuild.input.6urnt5pj.fasta
[16:56:23] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_12.
[16:56:23] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_12/A_12_0/FC_12_0_0/hmmalign.results.ymxah4uj) into base alignment (/tmp/sepp/output.av1ips1c/root/P_12/A_12_0/hmmbuild.input.6urnt5pj.fasta).
[16:56:23] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_13/A_13_0/hmmbuild.model.2d3s2u8f, fragments:/tmp/sepp/output.av1ips1c/root/P_13/A_13_0/FC_13_0_0/hmmalign.frag.l_usa3f8.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_13/A_13_0/hmmbuild.input.jr8s_erv.fasta
[16:56:23] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_13.
[16:56:23] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_13/A_13_0/FC_13_0_0/hmmalign.results.d_35q1so) into base alignment (/tmp/sepp/output.av1ips1c/root/P_13/A_13_0/hmmbuild.input.jr8s_erv.fasta).
[16:56:23] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_14.
[16:56:23] jobs.py (line 132):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.av1ips1c/root/P_15/A_15_0/hmmbuild.model.dv8w83cx, fragments:/tmp/sepp/output.av1ips1c/root/P_15/A_15_0/FC_15_0_0/hmmalign.frag.9w993dr8.fasta, trim:False, base_alignment:/tmp/sepp/output.av1ips1c/root/P_15/A_15_0/hmmbuild.input.3cj6ii37.fasta
[16:56:23] exhaustive.py (line 152):     INFO: Merging sub-alignments for placement problem : P_15.
[16:56:23] alignment.py (line 558):     INFO: Merging extension sto file (/tmp/sepp/output.av1ips1c/root/P_15/A_15_0/FC_15_0_0/hmmalign.results.8m52h9ds) into base alignment (/tmp/sepp/output.av1ips1c/root/P_15/A_15_0/hmmbuild.input.3cj6ii37.fasta).
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/sepp/scheduler.py", line 74, in __call__
    return self.run()
  File "/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/sepp/jobs.py", line 154, in run
    if self.read_stderr() else 'No error messages available']))
sepp.scheduler.JobError: The following execution failed:
/home/kys123/miniconda3/envs/qiime2-2019.10/bin/pplacer --out-dir /tmp/sepp/output.av1ips1c/root/P_1 -j 1 -r /tmp/sepp/output.av1ips1c/root/P_1/pplacer.backbone.jzppelmb.fasta -s /home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info -t /tmp/sepp/output.av1ips1c/root/P_1/pplacer.tree.9f30flgb.tre --groups 10 /tmp/sepp/output.av1ips1c/root/P_1/pplacer.extended.0.mkf0pxc2.fasta
No error messages available
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kys123/miniconda3/envs/qiime2-2019.10/bin/run_sepp.py", line 26, in <module>
    ExhaustiveAlgorithm().run()
  File "/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/sepp/algorithm.py", line 174, in run
    if (not JobPool().wait_for_all_jobs()):
  File "/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/sepp/scheduler.py", line 365, in wait_for_all_jobs
    result.get()
  File "/home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
sepp.scheduler.JobError: The following execution failed:
/home/kys123/miniconda3/envs/qiime2-2019.10/bin/pplacer --out-dir /tmp/sepp/output.av1ips1c/root/P_1 -j 1 -r /tmp/sepp/output.av1ips1c/root/P_1/pplacer.backbone.jzppelmb.fasta -s /home/kys123/miniconda3/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info -t /tmp/sepp/output.av1ips1c/root/P_1/pplacer.tree.9f30flgb.tre --groups 10 /tmp/sepp/output.av1ips1c/root/P_1/pplacer.extended.0.mkf0pxc2.fasta
No error messages available
```

I am asking if this problem is expected when I get the warning summary like below after commanding `pytest`.
I commanded `pytest` and got this message both before and after downloading the folder 'pro_ref'.
```
tests/test_place_seqs.py::place_seqs_tests::test_run_place_seqs_pipeline_sepp - SystemExit: 1
========================== 1 failed, 60 passed, 1 warning in 153.42s (0:02:33) ========================

```

How can I break away this problem? Please give me a hand to solve this problem.

Best,

Ko

**Comment by gavinmdouglas** [comment]
Hi there,

The last plugin version for PICRUSt2 was for QIIME 2 version 2021.11 - I would suggest installing that specific version and using the plugin. Alternatively, you can use the standalone version as well outside of QIIME 2.


All the best,

Gavin
