### ISSUE TITLE
Error with hsp.py step with tutorial data

### ISSUE THREAD

**Issue by sjackrel** [picrust/picrust2#320]
Hi, I am trying to run the tutorial data and am getting stuck at the second command. I've tried within and without the -e parameter. Command and error below. 

Sara

hsp.py -i 16S -t out.tre -o marker_predicted_and_nsti.tsv.gz -p 1 -n -e float 0

Traceback (most recent call last):
  File "/home/sjackrel/miniconda3/envs/picrust2/bin/hsp.py", line 8, in <module>
    from picrust2.wrap_hsp import castor_hsp_workflow
  File "/home/sjackrel/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/wrap_hsp.py", line 10, in <module>
    from joblib import Parallel, delayed
  File "/home/sjackrel/miniconda3/envs/picrust2/lib/python3.6/site-packages/joblib/__init__.py", line 129, in <module>
    from .parallel import Parallel
  File "/home/sjackrel/miniconda3/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 23, in <module>
    from contextlib import nullcontext
ImportError: cannot import name 'nullcontext'

**Comment by gavinmdouglas** [comment]
Hi there, 

This seems like an incompatibility with python 3.6 and the contextlib package for some reason -- see this issue too: https://stackoverflow.com/questions/69520829/openai-gym-attributeerror-module-contextlib-has-no-attribute-nullcontext

**Comment by gavinmdouglas** [comment]
Is the problem resolved if you install a higher Python version?

**Comment by sjackrel** [comment]
Yes, thank you!
