### ISSUE TITLE
Error in Picrust2_pipeline.py

### ISSUE THREAD

**Issue by Mirabelle0116** [picrust/picrust2#325]
Hello!!!!
when I use function picrust2_pipeline.py ,here is an error
Traceback (most recent call last):
  File "/home/data/t060452/.local/bin/picrust2_pipeline.py", line 4, in <module>
    __import__('pkg_resources').require('PICRUSt2==2.5.2')
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3324, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3298, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3336, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 629, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 868, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PICRUSt2==2.5.2' distribution was not found and is required by the application

when I use pytest,the errors are as follows:
FAILED picrust2-2.5.2/tests/test_place_seqs.py::place_seqs_tests::test_run_place_seqs_pipeline_sepp - SystemExit: 1
FAILED picrust2-2.5.2/tests/test_workflow.py::workflow_test::test_full_pipeline_tsv - SystemExit: 1
FAILED picrust2-2.5.2/tests/test_workflow.py::workflow_test::test_help_calls - SystemExit: 1
FAILED picrust2-2.5.2/tests/test_workflow.py::workflow_test::test_picrust2_pipeline_script - SystemExit: 1
FAILED picrust2-2.5.2/tests/test_workflow.py::workflow_test::test_picrust2_pipeline_script_per_seq_contrib_strat - SystemExit: 1
FAILED picrust2-2.5.2/tests/test_workflow.py::workflow_test::test_picrust2_pipeline_script_per_seq_contrib_strat_skip_norm - SystemExit: 1

So what should I do in order to use the function picrust2_pipeline.py?  
Thanks.
All the best.

**Comment by R-Wright-1** [comment]
Hi, it looks like when you're running the picrust2_pipeline.py script, it isn't able to find the PICRUSt2 package. Did you follow the instructions [here](https://github.com/picrust/picrust2/wiki/Installation) for installing PICRUSt2? Perhaps you installed the package in a conda/mamba environment and need to activate this prior to running the script, or maybe you moved the script and it isn't able to find the full package?

**Comment by R-Wright-1** [comment]
I am just closing this issue as there hasn't been any follow-up for a while. Please let me know if this needs to be reopened.
