### ISSUE TITLE
metagenome_pipeline.py error due to joblib(?)

### ISSUE THREAD

**Issue by xvazquezc** [picrust/picrust2#33]
Hi again,

I got this error several times while trying to run `metagenome_pipeline.py` (v 2.0.0-b.5) in our server (CentOS). It happens after few minutes and seems to be an issue with `joblib` v 0.12.1.
I forced the downgrade to `joblib=0.11` in the conda environment and still running after way longer than with 0.12.1 (~30 min)

```
$ metagenome_pipeline.py -i CHI4831_mothur_biom.reformated.full.json.biom -m CHI4831.picrust2.16S.tsv -f CHI4831.picrust2.KO.tsv -p 4 --strat_out -o CHI4831.picrust2.meta
Traceback (most recent call last):
  File "/home/z3382651/anaconda2/envs/picrust2-dev/bin/metagenome_pipeline.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/z3382651/bin/picrust2/scripts/metagenome_pipeline.py", line 102, in <module>
    main()
  File "/home/z3382651/bin/picrust2/scripts/metagenome_pipeline.py", line 88, in main
    output_normfile=True)
  File "/home/z3382651/bin/picrust2/picrust2/metagenome_pipeline.py", line 103, in run_metagenome_pipeline
    strat_out=strat_out))
  File "/home/z3382651/bin/picrust2/picrust2/metagenome_pipeline.py", line 174, in funcs_by_sample
    for sample in sample_ids)
  File "/home/z3382651/anaconda2/envs/picrust2-dev/lib/python3.6/site-packages/joblib/parallel.py", line 962, in __call__
    self.retrieve()
  File "/home/z3382651/anaconda2/envs/picrust2-dev/lib/python3.6/site-packages/joblib/parallel.py", line 865, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/z3382651/anaconda2/envs/picrust2-dev/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 515, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/z3382651/anaconda2/envs/picrust2-dev/lib/python3.6/site-packages/joblib/externals/loky/_base.py", line 431, in result
    return self.__get_result()
  File "/home/z3382651/anaconda2/envs/picrust2-dev/lib/python3.6/site-packages/joblib/externals/loky/_base.py", line 382, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A process in the executor was terminated abruptly while the future was running or pending.
```

Cheers,
Xabi

**Comment by gavinmdouglas** [comment]
Hi Xabi,

I haven't run into this issue before. How much memory does your server have? Does this command work if you drop the ```--strat_out``` option? It can take a really long time to generate the stratified results if you have a lot of input ASVs (e.g. tens of 1000s).

Gavin

**Comment by xvazquezc** [comment]
I ended filtering my dataset and with ~1000 taxa I could run it without issues with any `joblib` version with and without the `--strat_out ` option.
Likely a memory issue.
