### ISSUE TITLE
Error runnig picrust due to cannot import name '_convert_node_to_root_polytomy'

### ISSUE THREAD

**Issue by Zathzk** [picrust/picrust2#339]
i am trying to run the [Chemrein](https://en.wikipedia.org/wiki/Chemerin) tutorial mention in the picrust page but when i try to exectue this cmd:
 **place_seqs.py -s seqs.fna -o out.tre -p 1 --intermediate place_working -t sepp --verbose**

**i got this error message:**

hmmalign --trim --dna --mapali /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --informat FASTA -o place_working/query_align.stockholm /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.hmm seqs.fna

All raw input sequences were the same length (400)

run_sepp.py --tree /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --raxml /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info --cpu 1 --molecule dna --outdir place_working/sepp_out -seed 297834 --alignment /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --fragment place_working/study_seqs_filtered.fasta

Error running this command:
run_sepp.py --tree /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --raxml /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info --cpu 1 --molecule dna --outdir place_working/sepp_out -seed 297834 --alignment /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --fragment place_working/study_seqs_filtered.fasta

Standard error of the above failed command:
Traceback (most recent call last):
  File "/home/kalai/miniconda3/envs/picrust2/bin/run_sepp.py", line 3, in <module>
    from sepp.exhaustive import ExhaustiveAlgorithm
  File "/home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/exhaustive.py", line 6, in <module>
    from sepp.algorithm import AbstractAlgorithm
  File "/home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/algorithm.py", line 11, in <module>
    from sepp.tree import PhylogeneticTree
  File "/home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/tree.py", line 25, in <module>
    from dendropy.datamodel.treemodel import _convert_node_to_root_polytomy as \
**ImportError: cannot import name '_convert_node_to_root_polytomy' from 'dendropy.datamodel.treemodel' (/home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/dendropy/datamodel/treemodel/__init__.py)**

**so i searched for sultion and tried this [refference](https://github.com/smirarab/sepp/pull/126#issuecomment-1636698661)**
downgrading from dendropy 4.6.1 to dendropy 4.5.2. however i ran into another problem, this time there is **no error message available**

 **place_seqs.py -s seqs.fna -o out.tre -p 1 --intermediate place_working -t sepp --verbose**

hmmalign --trim --dna --mapali /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --informat FASTA -o place_working/query_align.stockholm /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.hmm seqs.fna

All raw input sequences were the same length (400)

run_sepp.py --tree /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --raxml /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info --cpu 1 --molecule dna --outdir place_working/sepp_out -seed 297834 --alignment /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --fragment place_working/study_seqs_filtered.fasta

Error running this command:
run_sepp.py --tree /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --raxml /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info --cpu 1 --molecule dna --outdir place_working/sepp_out -seed 297834 --alignment /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --fragment place_working/study_seqs_filtered.fasta

Standard error of the above failed command:
[16:11:42] config.py (line 349):     INFO: Seed number: 297834
[16:11:42] algorithm.py (line 258):     INFO: Reading input alignment: <_io.TextIOWrapper name='/home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna' mode='r' encoding='UTF-8'>
[16:11:42] algorithm.py (line 265):     INFO: Reading input tree: <_io.TextIOWrapper name='/home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre' mode='r' encoding='UTF-8'>
[16:11:43] algorithm.py (line 238):     INFO: Decomposition Sizes are set to alignment: 2000 placement: 2000
[16:11:44] exhaustive.py (line 350):     INFO: Breaking into 16 placement subsets.
[16:11:45] exhaustive.py (line 397):     INFO: Breaking into 16 alignment subsets.
[16:11:45] filemgr.py (line 129):     INFO: Root temp directory built: /tmp/sepp/output.5zp54_ek
[16:11:45] exhaustive.py (line 412):     INFO: Breaking each alignment subset into 1 fragment chunks.
[16:11:45] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_0/A_0_0/hmmbuild.input.qd_oab9r.fasta
[16:11:46] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_1/A_1_0/hmmbuild.input.33m76xuy.fasta
[16:11:46] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_2/A_2_0/hmmbuild.input.zlgaaphn.fasta
[16:11:46] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_3/A_3_0/hmmbuild.input.pb_wxr37.fasta
[16:11:46] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_4/A_4_0/hmmbuild.input.j0ce8n_m.fasta
[16:11:46] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_5/A_5_0/hmmbuild.input.w5pa_r6c.fasta
[16:11:47] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_6/A_6_0/hmmbuild.input.ccuwc_4l.fasta
[16:11:47] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_7/A_7_0/hmmbuild.input.et31sokx.fasta
[16:11:47] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_8/A_8_0/hmmbuild.input.8nskshma.fasta
[16:11:47] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_9/A_9_0/hmmbuild.input.x_cq5crr.fasta
[16:11:47] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_10/A_10_0/hmmbuild.input.du6sjb38.fasta
[16:11:48] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_11/A_11_0/hmmbuild.input.ftjmdsuf.fasta
[16:11:48] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_12/A_12_0/hmmbuild.input.oi52ui6s.fasta
[16:11:48] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_13/A_13_0/hmmbuild.input.v8hrxy8h.fasta
[16:11:48] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_14/A_14_0/hmmbuild.input._ea23t3y.fasta
[16:11:48] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.5zp54_ek/root/P_15/A_15_0/hmmbuild.input.hk4b2_o0.fasta
[16:11:49] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_0/A_0_0/hmmbuild.model.71f500qb, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_0/A_0_0/FC_0_0_0/hmmsearch.results.7waoyjh_
[16:11:49] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_1/A_1_0/hmmbuild.model.wzw4lmo2, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_1/A_1_0/FC_1_0_0/hmmsearch.results.01q6znzq
[16:11:49] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_2/A_2_0/hmmbuild.model.ok1sl_y9, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_2/A_2_0/FC_2_0_0/hmmsearch.results.h0ghdk3h
[16:11:49] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_3/A_3_0/hmmbuild.model.8w9tvipw, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_3/A_3_0/FC_3_0_0/hmmsearch.results.gv9x3lrj
[16:11:50] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_4/A_4_0/hmmbuild.model.1ew_o6qs, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_4/A_4_0/FC_4_0_0/hmmsearch.results.wpcb9nm0
[16:11:50] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_5/A_5_0/hmmbuild.model.sosd_1kr, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_5/A_5_0/FC_5_0_0/hmmsearch.results.jb4kdr54
[16:11:50] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_6/A_6_0/hmmbuild.model.dnv2q60j, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_6/A_6_0/FC_6_0_0/hmmsearch.results.se00ps9s
[16:11:50] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_7/A_7_0/hmmbuild.model.tq_yuqag, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_7/A_7_0/FC_7_0_0/hmmsearch.results.l4kc_05t
[16:11:50] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_8/A_8_0/hmmbuild.model.zliai6va, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_8/A_8_0/FC_8_0_0/hmmsearch.results.siviiht5
[16:11:51] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_9/A_9_0/hmmbuild.model.01bh3z82, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_9/A_9_0/FC_9_0_0/hmmsearch.results.4e27dyl9
[16:11:51] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_10/A_10_0/hmmbuild.model.5n0l3t0m, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_10/A_10_0/FC_10_0_0/hmmsearch.results.ia8pdxxt
[16:11:51] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_11/A_11_0/hmmbuild.model.as8c4e4t, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_11/A_11_0/FC_11_0_0/hmmsearch.results.yp_r0tit
[16:11:51] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_12/A_12_0/hmmbuild.model.ypbtml4t, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_12/A_12_0/FC_12_0_0/hmmsearch.results.6ww00o0w
[16:11:52] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_13/A_13_0/hmmbuild.model.n1pney03, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_13/A_13_0/FC_13_0_0/hmmsearch.results.wsbee_hc
[16:11:52] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_14/A_14_0/hmmbuild.model.fz7lb1xy, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_14/A_14_0/FC_14_0_0/hmmsearch.results.zyas34vo
[16:11:52] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_15/A_15_0/hmmbuild.model.al95m5tf, fragments:/tmp/sepp/output.5zp54_ek/fragment_chunks/fragment_chunk_0unem3r_q.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.5zp54_ek/root/P_15/A_15_0/FC_15_0_0/hmmsearch.results.dbivdrul
[16:11:52] exhaustive.py (line 80):  WARNING: Fragments [] are not scored against any subset
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_0.
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_1.
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_2.
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_3.
[16:11:52] jobs.py (line 131):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_9/A_9_0/hmmbuild.model.01bh3z82, fragments:/tmp/sepp/output.5zp54_ek/root/P_9/A_9_0/FC_9_0_0/hmmalign.frag.waqxz2k4.fasta, trim:False, base_alignment:/tmp/sepp/output.5zp54_ek/root/P_9/A_9_0/hmmbuild.input.x_cq5crr.fasta
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_4.
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_5.
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_6.
[16:11:52] jobs.py (line 131):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_11/A_11_0/hmmbuild.model.as8c4e4t, fragments:/tmp/sepp/output.5zp54_ek/root/P_11/A_11_0/FC_11_0_0/hmmalign.frag.t48txjup.fasta, trim:False, base_alignment:/tmp/sepp/output.5zp54_ek/root/P_11/A_11_0/hmmbuild.input.ftjmdsuf.fasta
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_7.
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_8.
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_9.
[16:11:52] alignment.py (line 556):     INFO: Merging extension sto file (/tmp/sepp/output.5zp54_ek/root/P_9/A_9_0/FC_9_0_0/hmmalign.results.fj5lyusc) into base alignment (/tmp/sepp/output.5zp54_ek/root/P_9/A_9_0/hmmbuild.input.x_cq5crr.fasta).
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_10.
[16:11:52] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_11.
[16:11:52] alignment.py (line 556):     INFO: Merging extension sto file (/tmp/sepp/output.5zp54_ek/root/P_11/A_11_0/FC_11_0_0/hmmalign.results.t87rlwqa) into base alignment (/tmp/sepp/output.5zp54_ek/root/P_11/A_11_0/hmmbuild.input.ftjmdsuf.fasta).
[16:11:53] jobs.py (line 131):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_12/A_12_0/hmmbuild.model.ypbtml4t, fragments:/tmp/sepp/output.5zp54_ek/root/P_12/A_12_0/FC_12_0_0/hmmalign.frag.to9810fg.fasta, trim:False, base_alignment:/tmp/sepp/output.5zp54_ek/root/P_12/A_12_0/hmmbuild.input.oi52ui6s.fasta
[16:11:53] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_12.
[16:11:53] alignment.py (line 556):     INFO: Merging extension sto file (/tmp/sepp/output.5zp54_ek/root/P_12/A_12_0/FC_12_0_0/hmmalign.results.yoopqhla) into base alignment (/tmp/sepp/output.5zp54_ek/root/P_12/A_12_0/hmmbuild.input.oi52ui6s.fasta).
[16:11:53] jobs.py (line 131):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.5zp54_ek/root/P_13/A_13_0/hmmbuild.model.n1pney03, fragments:/tmp/sepp/output.5zp54_ek/root/P_13/A_13_0/FC_13_0_0/hmmalign.frag.8nh16bh5.fasta, trim:False, base_alignment:/tmp/sepp/output.5zp54_ek/root/P_13/A_13_0/hmmbuild.input.v8hrxy8h.fasta
[16:11:53] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_13.
[16:11:53] alignment.py (line 556):     INFO: Merging extension sto file (/tmp/sepp/output.5zp54_ek/root/P_13/A_13_0/FC_13_0_0/hmmalign.results.dzt7ffpb) into base alignment (/tmp/sepp/output.5zp54_ek/root/P_13/A_13_0/hmmbuild.input.v8hrxy8h.fasta).
[16:11:53] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_14.
[16:11:53] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_15.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/kalai/miniconda3/envs/picrust2/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/scheduler.py", line 74, in __call__
    return self.run()
  File "/home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/jobs.py", line 150, in run
    raise JobError("\n".join([
sepp.scheduler.JobError: The following execution failed:
/home/kalai/miniconda3/envs/picrust2/bin/pplacer --out-dir /tmp/sepp/output.5zp54_ek/root/P_9 -j 1 -r /tmp/sepp/output.5zp54_ek/root/P_9/pplacer.backbone.iudu1qy8.fasta -s /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info -t /tmp/sepp/output.5zp54_ek/root/P_9/pplacer.tree.lo8ki89o.tre --groups 10 /tmp/sepp/output.5zp54_ek/root/P_9/pplacer.extended.0.sscnv87n.fasta
No error messages available
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kalai/miniconda3/envs/picrust2/bin/run_sepp.py", line 26, in <module>
    ExhaustiveAlgorithm().run()
  File "/home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/algorithm.py", line 174, in run
    if (not JobPool().wait_for_all_jobs()):
  File "/home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/scheduler.py", line 365, in wait_for_all_jobs
    result.get()
  File "/home/kalai/miniconda3/envs/picrust2/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
sepp.scheduler.JobError: The following execution failed:
/home/kalai/miniconda3/envs/picrust2/bin/pplacer --out-dir /tmp/sepp/output.5zp54_ek/root/P_9 -j 1 -r /tmp/sepp/output.5zp54_ek/root/P_9/pplacer.backbone.iudu1qy8.fasta -s /home/kalai/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info -t /tmp/sepp/output.5zp54_ek/root/P_9/pplacer.tree.lo8ki89o.tre --groups 10 /tmp/sepp/output.5zp54_ek/root/P_9/pplacer.extended.0.sscnv87n.fasta
**No error messages available**

**Comment by R-Wright-1** [comment]
Hi there,

Apologies for the incredibly slow response. How did you install PICRUSt2, and have you tried installing it in a new environment from the source code? 

Robyn

**Comment by R-Wright-1** [comment]
I am closing this issue as there has been no further response.
