### ISSUE TITLE
PICRTUST 2  No such file or directory: 'hmmalign'

### ISSUE THREAD

**Issue by kesava31** [picrust/picrust2#344]
Hi
I m running the PICRTUST 2 using fna file and tsv abundance file as a input. I m getting an error see below. Could you guide me how to fix it.
b-an01 [/proj/nobackup/hpc2nstor2023-021/Function/Prediction]$ picrust2_pipeline.py -s OTU.fna.fasta -i cleaned_OTU_table.tsv -o picrust4_out_pipeline -p 1

Error running this command:
place_seqs.py --study_fasta OTU.fna.fasta --ref_dir /hpc2n/eb/software/PICRUSt2/2.5.2-foss-2022b/lib/python3.10/site-packages/picrust2/default_files/prokaryotic/pro_ref --out_tree picrust4_out_pipeline/out.tre --processes 1 --intermediate picrust4_out_pipeline/intermediate/place_seqs --min_align 0.8 --chunk_size 5000 --placement_tool epa-ng

Standard error of the above failed command:
Traceback (most recent call last):
  File "/hpc2n/eb/software/PICRUSt2/2.5.2-foss-2022b/bin/place_seqs.py", line 109, in <module>
    main()
  File "/hpc2n/eb/software/PICRUSt2/2.5.2-foss-2022b/bin/place_seqs.py", line 85, in main
    place_seqs_pipeline(study_fasta=args.study_fasta,
  File "/hpc2n/eb/software/PICRUSt2/2.5.2-foss-2022b/lib/python3.10/site-packages/picrust2/place_seqs.py", line 45, in place_seqs_pipeline
    system_call_check("hmmalign --trim --dna --mapali " +
  File "/hpc2n/eb/software/PICRUSt2/2.5.2-foss-2022b/lib/python3.10/site-packages/picrust2/util.py", line 235, in system_call_check
    return_value = call(cmd, stdout=stdout_fh,
  File "/hpc2n/eb/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/hpc2n/eb/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/hpc2n/eb/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hmmalign'

**Comment by R-Wright-1** [comment]
Hi there,

That issue would seem to be that it can't find the `hmmalign` program installed in your path. Can you try running `which hmmalign` in the environment you're using and see if that works/what the output is? If it says that this isn't installed, then you could try installing it following the instructions [here](https://anaconda.org/bioconda/hmmer) and then re-running the PICRUSt2 command. 

Robyn

**Comment by kesava31** [comment]
Hi Wright
Thanks for your response. I installed now and it worked fine.
