### ISSUE TITLE
During pytest place_seqs.py fails and cannot run the full pipeline

### ISSUE THREAD

**Issue by rassanjorjo** [picrust/picrust2#347]
I have reinstalled picrust a dozen times already but the place_seqs.py always fails. I dont have qiime2 already in my system. what could be possibly wrong? Please help. thank you!

platform linux -- Python 3.8.19, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/rey/picrust2-2.5.2
plugins: cov-5.0.0
collected 61 items

tests/test_hsp.py ........                                                                                       [ 13%]
tests/test_metagenome_pipeline.py ...............                                                                [ 37%]
tests/test_pathway_pipeline.py ....                                                                              [ 44%]
tests/test_place_seqs.py ........F                                                                               [ 59%]
tests/test_util.py ....................                                                                          [ 91%]
tests/test_workflow.py .....                                                                                     [100%]

======================================================= FAILURES =======================================================
__________________________________ place_seqs_tests.test_run_place_seqs_pipeline_sepp __________________________________

self = <tests.test_place_seqs.place_seqs_tests testMethod=test_run_place_seqs_pipeline_sepp>

    def test_run_place_seqs_pipeline_sepp(self):
        '''Basic test of full place seqs pipeline with SEPP. Just run to
           see if any errors occur'''
        with TemporaryDirectory() as temp_dir:
            tmp_tree = path.join(temp_dir, "out.tre")

>           place_seqs_pipeline(study_fasta=test_study_seqs,
                                ref_dir=default_ref_dir,
                                placement_tool="sepp",
                                out_tree=tmp_tree,
                                threads=1,
                                out_dir=temp_dir,
                                min_align=0.8,
                                chunk_size=5000,
                                verbose=True)

tests/test_place_seqs.py:160:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
picrust2/place_seqs.py:95: in place_seqs_pipeline
    run_sepp(tree=tree,
picrust2/place_seqs.py:458: in run_sepp
    system_call_check(sepp_command, print_command=print_cmds,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = ['run_sepp.py', '--tree', '/home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre', '--raxml', '/home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info', '--cpu', ...]
print_command = True, print_stdout = True, print_stderr = True

    def system_call_check(cmd, print_command=False, print_stdout=False,
                          print_stderr=False):
        '''Run system command and throw and error if return is not 0. Input command
        can be a list containing the command or a string.'''

        # Convert command to list if input as string.
        if type(cmd) is str:
            cmd = cmd.split()

        # Print command out if option set.
        if print_command:
            print(" ".join(cmd), file=sys.stderr)

        stdout_log = ""
        stderr_log = ""

        # Write stdout and stderr of command to temporary files.
        # Only output the content of these files if the job fails.
        with TemporaryDirectory() as temp_dir:

            stdout_file = join(temp_dir, "stdout.txt")
            stderr_file = join(temp_dir, "stderr.txt")

            with open(stdout_file, "wb") as stdout_fh, \
                 open(stderr_file, "wb") as stderr_fh:

                return_value = call(cmd, stdout=stdout_fh,
                                    stderr=stderr_fh)

            # Capture stdout and stderr.
            with open(stdout_file, 'r') as stdout_fh:
                stdout_log = stdout_fh.read()

            with open(stderr_file, 'r') as stderr_fh:
                stderr_log = stderr_fh.read()

            # Exit with error if command did not finish successfully.
            if return_value != 0:
                print("\nError running this command:\n" + " ".join(cmd),
                      file=sys.stderr)

                if stdout_log:
                    print("\nStandard output of the above failed command:\n" +
                          stdout_log, file=sys.stderr)

                if stderr_log:
                    print("\nStandard error of the above failed command:\n" +
                          stderr_log, file=sys.stderr)

>               sys.exit(1)
E               SystemExit: 1

picrust2/util.py:258: SystemExit
------------------------------------------------- Captured stdout call -------------------------------------------------

------------------------------------------------- Captured stderr call -------------------------------------------------
hmmalign --trim --dna --mapali /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --informat FASTA -o /tmp/tmprslmk87r/query_align.stockholm /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.hmm /home/rey/picrust2-2.5.2/tests/test_data/place_seqs/study_seqs_test.fasta

All raw input sequences were the same length (400)

run_sepp.py --tree /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --raxml /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info --cpu 1 --molecule dna --outdir /tmp/tmprslmk87r/sepp_out -seed 297834 --alignment /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --fragment /tmp/tmprslmk87r/study_seqs_filtered.fasta

Error running this command:
run_sepp.py --tree /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --raxml /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info --cpu 1 --molecule dna --outdir /tmp/tmprslmk87r/sepp_out -seed 297834 --alignment /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --fragment /tmp/tmprslmk87r/study_seqs_filtered.fasta

Standard error of the above failed command:
[18:59:07] config.py (line 349):     INFO: Seed number: 297834
[18:59:07] algorithm.py (line 258):     INFO: Reading input alignment: <_io.TextIOWrapper name='/home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna' mode='r' encoding='UTF-8'>
[18:59:07] algorithm.py (line 265):     INFO: Reading input tree: <_io.TextIOWrapper name='/home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre' mode='r' encoding='UTF-8'>
[18:59:08] algorithm.py (line 238):     INFO: Decomposition Sizes are set to alignment: 2000 placement: 2000
[18:59:10] exhaustive.py (line 350):     INFO: Breaking into 16 placement subsets.
[18:59:12] exhaustive.py (line 397):     INFO: Breaking into 16 alignment subsets.
[18:59:12] filemgr.py (line 129):     INFO: Root temp directory built: /tmp/sepp/output.ziutryl9
[18:59:12] exhaustive.py (line 412):     INFO: Breaking each alignment subset into 1 fragment chunks.
[18:59:12] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_0/A_0_0/hmmbuild.input.l0dv1zqq.fasta
[18:59:13] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_1/A_1_0/hmmbuild.input.js7bzx9z.fasta
[18:59:13] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_2/A_2_0/hmmbuild.input.injtgju8.fasta
[18:59:13] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_3/A_3_0/hmmbuild.input.jp54cb6i.fasta
[18:59:14] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_4/A_4_0/hmmbuild.input.vd_lvhg6.fasta
[18:59:14] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_5/A_5_0/hmmbuild.input.c32y13u4.fasta
[18:59:15] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_6/A_6_0/hmmbuild.input.hnmfk8ch.fasta
[18:59:15] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_7/A_7_0/hmmbuild.input.p_jcl0c5.fasta
[18:59:15] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_8/A_8_0/hmmbuild.input.qglp5vtk.fasta
[18:59:16] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_9/A_9_0/hmmbuild.input.qk6u4w4j.fasta
[18:59:16] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_10/A_10_0/hmmbuild.input.0kmir8wz.fasta
[18:59:16] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_11/A_11_0/hmmbuild.input.2r4vfbmi.fasta
[18:59:17] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_12/A_12_0/hmmbuild.input.of5d9sau.fasta
[18:59:17] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_13/A_13_0/hmmbuild.input.v1feofeq.fasta
[18:59:17] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_14/A_14_0/hmmbuild.input.vmiol6a5.fasta
[18:59:18] jobs.py (line 131):     INFO: Finished hmmbuild Job with input: /tmp/sepp/output.ziutryl9/root/P_15/A_15_0/hmmbuild.input.974lvlxz.fasta
[18:59:18] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_0/A_0_0/hmmbuild.model.sxjfux_w, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_0/A_0_0/FC_0_0_0/hmmsearch.results.09y0blu1
[18:59:18] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_1/A_1_0/hmmbuild.model.iys7buk2, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_1/A_1_0/FC_1_0_0/hmmsearch.results.1w_s_2tk
[18:59:18] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_2/A_2_0/hmmbuild.model.15l8k4od, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_2/A_2_0/FC_2_0_0/hmmsearch.results.yy90t3p4
[18:59:18] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_3/A_3_0/hmmbuild.model.sh39pw8g, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_3/A_3_0/FC_3_0_0/hmmsearch.results.dis4dy4w
[18:59:18] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_4/A_4_0/hmmbuild.model.m9jzs8mk, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_4/A_4_0/FC_4_0_0/hmmsearch.results.dz1hmdz9
[18:59:18] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_5/A_5_0/hmmbuild.model.z7c6oilt, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_5/A_5_0/FC_5_0_0/hmmsearch.results.gep5wjkr
[18:59:18] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_6/A_6_0/hmmbuild.model.hu245b99, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_6/A_6_0/FC_6_0_0/hmmsearch.results.9znx47ju
[18:59:18] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_7/A_7_0/hmmbuild.model.1o0_7nh_, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_7/A_7_0/FC_7_0_0/hmmsearch.results.urvm_nob
[18:59:18] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_8/A_8_0/hmmbuild.model.egv_5eiv, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_8/A_8_0/FC_8_0_0/hmmsearch.results.h8n2qx_w
[18:59:18] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_9/A_9_0/hmmbuild.model.gkq4uvvu, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_9/A_9_0/FC_9_0_0/hmmsearch.results.1uayjdtd
[18:59:18] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_10/A_10_0/hmmbuild.model.qu3znbk5, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_10/A_10_0/FC_10_0_0/hmmsearch.results.y6_19w1g
[18:59:19] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_11/A_11_0/hmmbuild.model.mvnj9xxc, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_11/A_11_0/FC_11_0_0/hmmsearch.results.a9dv_ma4
[18:59:19] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_12/A_12_0/hmmbuild.model.t05fw19c, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_12/A_12_0/FC_12_0_0/hmmsearch.results.wt0ddxve
[18:59:19] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_13/A_13_0/hmmbuild.model.52vhlqai, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_13/A_13_0/FC_13_0_0/hmmsearch.results.9m48wig0
[18:59:19] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_14/A_14_0/hmmbuild.model.pxsw6cn5, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_14/A_14_0/FC_14_0_0/hmmsearch.results.zigt2owg
[18:59:19] jobs.py (line 131):     INFO: Finished hmmsearch Job with input: model:/tmp/sepp/output.ziutryl9/root/P_15/A_15_0/hmmbuild.model.ho7x3rjb, fragments:/tmp/sepp/output.ziutryl9/fragment_chunks/fragment_chunk_0hhu1zq7u.fasta, elim:99999999, filter:False, output:/tmp/sepp/output.ziutryl9/root/P_15/A_15_0/FC_15_0_0/hmmsearch.results.f0zmg87n
[18:59:19] exhaustive.py (line 80):  WARNING: Fragments [] are not scored against any subset
[18:59:19] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_0.
[18:59:19] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_1.
[18:59:19] jobs.py (line 131):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.ziutryl9/root/P_11/A_11_0/hmmbuild.model.mvnj9xxc, fragments:/tmp/sepp/output.ziutryl9/root/P_11/A_11_0/FC_11_0_0/hmmalign.frag.q9pw3at8.fasta, trim:False, base_alignment:/tmp/sepp/output.ziutryl9/root/P_11/A_11_0/hmmbuild.input.2r4vfbmi.fasta
[18:59:19] jobs.py (line 131):     INFO: Finished hmmalign Job with input: model:/tmp/sepp/output.ziutryl9/root/P_12/A_12_0/hmmbuild.model.t05fw19c, fragments:/tmp/sepp/output.ziutryl9/root/P_12/A_12_0/FC_12_0_0/hmmalign.frag.n196udv8.fasta, trim:False, base_alignment:/tmp/sepp/output.ziutryl9/root/P_12/A_12_0/hmmbuild.input.of5d9sau.fasta
[18:59:19] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_2.
[18:59:19] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_3.
[18:59:20] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_4.
[18:59:20] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_5.
[18:59:20] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_6.
[18:59:20] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_7.
[18:59:20] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_8.
[18:59:20] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_9.
[18:59:21] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_10.
[18:59:21] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_11.
[18:59:21] alignment.py (line 556):     INFO: Merging extension sto file (/tmp/sepp/output.ziutryl9/root/P_11/A_11_0/FC_11_0_0/hmmalign.results.m_34mu_m) into base alignment (/tmp/sepp/output.ziutryl9/root/P_11/A_11_0/hmmbuild.input.2r4vfbmi.fasta).
[18:59:21] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_12.
[18:59:21] alignment.py (line 556):     INFO: Merging extension sto file (/tmp/sepp/output.ziutryl9/root/P_12/A_12_0/FC_12_0_0/hmmalign.results.e28wyw11) into base alignment (/tmp/sepp/output.ziutryl9/root/P_12/A_12_0/hmmbuild.input.of5d9sau.fasta).
[18:59:21] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_13.
[18:59:21] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_14.
[18:59:21] exhaustive.py (line 151):     INFO: Merging sub-alignments for placement problem : P_15.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/rey/miniconda3/envs/picrust2/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/rey/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/scheduler.py", line 74, in __call__
    return self.run()
  File "/home/rey/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/jobs.py", line 150, in run
    raise JobError("\n".join([
sepp.scheduler.JobError: The following execution failed:
/home/rey/miniconda3/envs/picrust2/bin/pplacer --out-dir /tmp/sepp/output.ziutryl9/root/P_11 -j 1 -r /tmp/sepp/output.ziutryl9/root/P_11/pplacer.backbone.3bmtzx2t.fasta -s /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info -t /tmp/sepp/output.ziutryl9/root/P_11/pplacer.tree.8mh_4hm2.tre --groups 10 /tmp/sepp/output.ziutryl9/root/P_11/pplacer.extended.0.l63bj2as.fasta
No error messages available
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rey/miniconda3/envs/picrust2/bin/run_sepp.py", line 26, in <module>
    ExhaustiveAlgorithm().run()
  File "/home/rey/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/algorithm.py", line 174, in run
    if (not JobPool().wait_for_all_jobs()):
  File "/home/rey/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/scheduler.py", line 365, in wait_for_all_jobs
    result.get()
  File "/home/rey/miniconda3/envs/picrust2/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
sepp.scheduler.JobError: The following execution failed:
/home/rey/miniconda3/envs/picrust2/bin/pplacer --out-dir /tmp/sepp/output.ziutryl9/root/P_11 -j 1 -r /tmp/sepp/output.ziutryl9/root/P_11/pplacer.backbone.3bmtzx2t.fasta -s /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info -t /tmp/sepp/output.ziutryl9/root/P_11/pplacer.tree.8mh_4hm2.tre --groups 10 /tmp/sepp/output.ziutryl9/root/P_11/pplacer.extended.0.l63bj2as.fasta
No error messages available
Traceback (most recent call last):
  File "/home/rey/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/jobs.py", line 150, in run
    raise JobError("\n".join([
sepp.scheduler.JobError: The following execution failed:
/home/rey/miniconda3/envs/picrust2/bin/pplacer --out-dir /tmp/sepp/output.ziutryl9/root/P_11 -j 1 -r /tmp/sepp/output.ziutryl9/root/P_11/pplacer.backbone.3bmtzx2t.fasta -s /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info -t /tmp/sepp/output.ziutryl9/root/P_11/pplacer.tree.8mh_4hm2.tre --groups 10 /tmp/sepp/output.ziutryl9/root/P_11/pplacer.extended.0.l63bj2as.fasta
No error messages available
Traceback (most recent call last):
  File "/home/rey/miniconda3/envs/picrust2/lib/python3.8/site-packages/sepp/jobs.py", line 150, in run
    raise JobError("\n".join([
sepp.scheduler.JobError: The following execution failed:
/home/rey/miniconda3/envs/picrust2/bin/pplacer --out-dir /tmp/sepp/output.ziutryl9/root/P_12 -j 1 -r /tmp/sepp/output.ziutryl9/root/P_12/pplacer.backbone.4upgh484.fasta -s /home/rey/picrust2-2.5.2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info -t /tmp/sepp/output.ziutryl9/root/P_12/pplacer.tree.4lc_bd7f.tre --groups 10 /tmp/sepp/output.ziutryl9/root/P_12/pplacer.extended.0.wfr64ivs.fasta
No error messages available

=============================================== short test summary info ================================================
FAILED tests/test_place_seqs.py::place_seqs_tests::test_run_place_seqs_pipeline_sepp - SystemExit: 1
======================================= 1 failed, 60 passed in 106.70s (0:01:46) =======================================

**Comment by R-Wright-1** [comment]
Hi there, could you see if the fix in issue #314 works?

**Comment by rassanjorjo** [comment]
Good day!

I tried to run as outlined in issue #314 but another error popped out after pip install --editable .

(picrust2-src) rey@H110M-DESK:~/picrust2-2.5.2$ pip install --editable .
/home/rey/miniconda3/envs/picrust2-src/bin/pip: line 3: import: command not found
/home/rey/miniconda3/envs/picrust2-src/bin/pip: line 4: import: command not found
from: can't read /var/mail/pip._internal.cli.main
/home/rey/miniconda3/envs/picrust2-src/bin/pip: line 9: syntax error near unexpected token `('
/home/rey/miniconda3/envs/picrust2-src/bin/pip: line 9: `    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])'

and i cannot run pytest successfully.


Thank you so much

**Comment by rassanjorjo** [comment]
Im using ubuntu on windows, RAM is at 12GB but an i3-6100 processor using a 64bit operating system

**Comment by R-Wright-1** [comment]
Hmm, I think that the RAM might be the issue. You can see in the [installation instructions](https://github.com/picrust/picrust2/wiki/Installation) that at least 16GB is needed - I think that trying the version within QIIME2 is your best bet.

**Comment by R-Wright-1** [comment]
I'm just closing this as there has been no further response.
