### ISSUE TITLE
ValueError: numpy.ufunc has the wrong size

### ISSUE THREAD

**Issue by colinbrislawn** [picrust/picrust2#56]
Good afternoon!

I received this error after doing a fresh install into a conda environment. I'm guessing it has to do with my current version of numpy, which might be too old for picrust2.

```
(picrust2) []$ conda list | grep numpy
numpy                     1.15.4           py36h7e9f1db_0  
numpy-base                1.15.4           py36hde5b4d6_0  
```

No specific version of numpy is pinned in the `picrust2-env.yaml`. Which version of numpy from which bioconda channel should I try to install? 

---

Main error:
```bash
_______________________ ERROR collecting tests/test_metagenome_pipeline.py _______________________
tests/test_metagenome_pipeline.py:10: in <module>
    import biom
../anaconda/envs/picrust2/lib/python3.6/site-packages/biom/__init__.py:51: in <module>
    from .table import Table
../anaconda/envs/picrust2/lib/python3.6/site-packages/biom/table.py:200: in <module>
    from ._filter import _filter
__init__.pxd:861: in init biom._filter (biom/_filter.c:6729)
    ???
E   ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
======================================== warnings summary ========================================
```

---

EDIT: Looks like this is an issue with a mismatch between numpy and the biom-format package that imports numpy. Neither numpy or biom-format are pinned. Here are the versions I have installed using pip: 
`biom-format     2.1.7      `
`numpy           1.15.4    `
Using conda, I also have these versions of numpy:
`numpy                     1.15.4           py36h7e9f1db_0    anaconda`
`numpy-base                1.15.4           py36hde5b4d6_0  `

**Comment by gavinmdouglas** [comment]
Hi there,

Were you installing v2.0.3-b? If you so you could use the current developmental YAML, which points to a particular version of pandas compatible with QIIME2: https://github.com/picrust/picrust2/blob/master/picrust2-env.yaml

Also just in case you were using a different approach be sure to be following the install documentation on this page: https://github.com/picrust/picrust2/wiki/Installation

I've been working with PICRUSt2 with biom-format 2.1.7 and numpy 1.12.1 as well as a different environment with biom-format 2.1.5 and 1.12.1.

I'll be making an update shortly so I'll be sure to tag compatible versions, thanks for pointing this out!

**Comment by colinbrislawn** [comment]
Yep, I don't the non-qiime2 install of picrust, following those exact instructions. 

I remove my previous conda environment, then tried again with that yaml file in the master branch. Ironically, I got a totally different error. 

```
[bris469@constance03 picrust2-2.0.3-b]$ conda env create -f picrust2-env.yaml 
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 1.20.0
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /people/bris469/bin/anaconda  (writable)
    default environment : /people/bris469/bin/anaconda
       envs directories : /people/bris469/bin/anaconda/envs
                          /people/bris469/.conda/envs
          package cache : /people/bris469/bin/anaconda/pkgs
                          /people/bris469/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /people/bris469/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-642.6.2.el6.x86_64 Red Hat Enterprise Linux Workstation/6.6 glibc/2.12    
                UID:GID : 3859:100

`$ /people/bris469/bin/anaconda/bin/conda-env create -f picrust2-env.yaml`




    Traceback (most recent call last):
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 78, in execute
        directory=os.getcwd())
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/conda_env/specs/__init__.py", line 20, in detect
        if spec.can_handle():
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/conda_env/env.py", line 80, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/conda_env/env.py", line 68, in from_yaml
        data = yaml.load(yamlstr)
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/ruamel_yaml/main.py", line 75, in load
        return loader.get_single_data()
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/ruamel_yaml/constructor.py", line 60, in get_single_data
        node = self.get_single_node()
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/ruamel_yaml/composer.py", line 53, in get_single_node
        document = self.compose_document()
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/ruamel_yaml/composer.py", line 76, in compose_document
        self.get_event()
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/ruamel_yaml/parser.py", line 136, in get_event
        self.current_event = self.state()
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/ruamel_yaml/parser.py", line 215, in parse_document_end
        token = self.peek_token()
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 144, in peek_token
        self.fetch_more_tokens()
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 239, in fetch_more_tokens
        return self.fetch_value()
      File "/people/bris469/bin/anaconda/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 598, in fetch_value
        self.get_mark())
    ScannerError: mapping values are not allowed here
      in "<byte string>", line 532, column 26:
            <!-- blob contrib key: blob_contributors:v21:6cbe35c9 ... 
                                 ^


```

**Comment by gavinmdouglas** [comment]
Hmm I haven't come across that before. It looks like maybe it's related to a malformed YAML file. I just double-checked that the file I pointed you to works with conda 4.5.12 at least. Any chance that you missing a colon or indent if you copied and pasted the YAML? Otherwise maybe upgrading conda to the latest version could fix the problem.

**Comment by colinbrislawn** [comment]
I messed up the YAML file when downloading it, but I got that sorted and was able to install picrust and all dependencies. I'm still getting this error:

```
______________ ERROR collecting tests/test_metagenome_pipeline.py _______________
tests/test_metagenome_pipeline.py:10: in <module>
    import biom
../anaconda/envs/picrust2/lib/python3.6/site-packages/biom/__init__.py:51: in <module>
    from .table import Table
../anaconda/envs/picrust2/lib/python3.6/site-packages/biom/table.py:200: in <module>
    from ._filter import _filter
__init__.pxd:861: in init biom._filter (biom/_filter.c:6729)
    ???
E   ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

```

I have this software installed
```
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
biom-format               2.1.7                    pypi_0    pypi
```

I'll try installing numpy 1.12.1  and see how it goes.

Thank you for all of your help!

**Comment by colinbrislawn** [comment]
I got the same error with biom-format 2.1.7 and numpy 1.12.1. 🤷‍♂️  Any ideas?

**Comment by gavinmdouglas** [comment]
It looks like this error occurs when biom-format is compiled against a different version of numpy than is currently installed (see: https://stackoverflow.com/questions/17709641/valueerror-numpy-dtype-has-the-wrong-size-try-recompiling).

Could you try running this in the picrust2 environment:

```
conda install pandas=0.22.0 numpy=1.12.1 scipy=0.19.1 biom-format=2.1.7
```

**Comment by colinbrislawn** [comment]
That worked for me! Thank you so much for helping me solve this!

I'll close this issue for now, but feel free to reopen if other folks are having this issue and we decide to update the yaml file.

**Comment by gavinmdouglas** [comment]
Ok great - I'll tag specific versions of the requirements in a future release to make sure this doesn't happen.

**Comment by colinbrislawn** [comment]
Cool cool.

Just to be complete, here is my full conda environment. 

```
(picrust2) [bris469@constance01 picrust2-2.0.3-b]$ conda list
# packages in environment at /people/bris469/bin/anaconda/envs/picrust2:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0               anacondar_1    r
atomicwrites              1.2.1                    pypi_0    pypi
attrs                     18.2.0                   pypi_0    pypi
binutils_impl_linux-64    2.31.1               h6176602_1    conda-forge
binutils_linux-64         2.31.1               h6176602_3    conda-forge
biom-format               2.1.7           py36h3010b51_1002    conda-forge
blas                      1.0                         mkl  
bwidget                   1.9.11                        1  
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.12.5                     0  
cairo                     1.14.12              h8948797_3  
certifi                   2018.11.29               py36_0  
click                     7.0                      pypi_0    pypi
coverage                  4.5.2                    pypi_0    pypi
curl                      7.63.0            hbc83047_1000  
epa-ng                    0.3.4                he860b03_2    bioconda
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1             h94bbf69_1005    conda-forge
fribidi                   1.0.5                h7b6447c_0  
future                    0.17.1                   pypi_0    pypi
gappa                     0.1.0                he860b03_0    bioconda
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_3    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
gfortran_impl_linux-64    7.3.0                hdf63c60_1    conda-forge
gfortran_linux-64         7.3.0                h553295d_3    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
glpk                      4.65              ha14ba45_1001    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gsl                       2.4                  h14c3975_4  
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_3    conda-forge
h5py                      2.9.0           nompi_py36hf008753_1102    conda-forge
harfbuzz                  1.9.0             he243708_1001    conda-forge
hdf5                      1.10.4          nompi_h11e915b_1105    conda-forge
hmmer                     3.2.1                hfc679d8_0    bioconda
icu                       58.2              hf484d3e_1000    conda-forge
intel-openmp              2019.1                      144  
joblib                    0.13.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
krb5                      1.16.1               h173b8e3_7  
libcurl                   7.63.0            h20c2e04_1000  
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h14c3975_1004    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libssh2                   1.8.0                h1ba5d50_4  
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
make                      4.2.1             h14c3975_2004    conda-forge
mkl                       2018.0.3                      1  
more-itertools            5.0.0                    pypi_0    pypi
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.12.1           py36he24570b_1  
openblas                  0.2.19                        2    conda-forge
openssl                   1.1.1a               h7b6447c_0  
pandas                    0.22.0           py36hf484d3e_0  
pango                     1.42.4               h049681c_0  
pcre                      8.42                 h439df22_0  
picrust2                  2.0.3b0                   dev_0    <develop>
pip                       19.0.1                   py36_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
pluggy                    0.8.1                    pypi_0    pypi
pthread-stubs             0.4               h14c3975_1001    conda-forge
py                        1.7.0                    pypi_0    pypi
pytest                    4.1.1                    pypi_0    pypi
pytest-cov                2.6.1                    pypi_0    pypi
python                    3.6.8                h0371630_0  
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
r-base                    3.5.1                h1e0a451_2    r
r-castor                  1.3.4           r351h29659fb_1000    conda-forge
r-naturalsort             0.1.3           r351h6115d3f_1001    conda-forge
r-rcpp                    1.0.0           r351h29659fb_1000    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
scipy                     0.19.1           py36h9976243_3  
setuptools                40.7.1                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tktable                   2.10                 h14c3975_0  
wheel                     0.32.3                   py36_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.2                h470a237_5    conda-forge
xorg-libx11               1.6.6             h14c3975_1000    conda-forge
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```
